import 'create_organization_command.dart';
import 'tenant_health_snapshot.dart';

/// Port for SuperAdmin data operations.
///
/// Concrete implementation: [SupabaseSuperAdminRepository].
/// All methods use the service_role client — never the anon client.
/// INV-4: Pure Dart interface — zero infrastructure dependencies.
abstract class ISuperAdminRepository {
  /// Atomically creates a new organization and records an 'ORG_CREATED' billing event.
  ///
  /// Returns the new organization's UUID.
  Future<String> createOrganization(CreateOrganizationCommand command);

  /// Inserts an invitation for the org's first admin.
  ///
  /// IDs and token are generated by the caller (INV-7: Deterministic Replay).
  Future<void> inviteFirstAdmin({
    required String orgId,
    required String email,
    required String token,
    required String invitationId,
    required DateTime expiresAtUtc,
    required String superAdminUserId,
  });

  /// Reads all tenant health snapshots from `super_admin_tenant_health_view`.
  Future<List<TenantHealthSnapshot>> getAllTenantHealth();

  /// Reads system audit log entries, optionally filtered by organization.
  Future<List<Map<String, dynamic>>> getSystemAuditLog({
    String? organizationId,
    String? severity,
    DateTime? fromDate,
    DateTime? toDate,
    int limit,
  });
}
