import 'archive_organization_command.dart';
import 'create_organization_command.dart';
import 'system_audit_log_entry.dart';
import 'tenant_health_snapshot.dart';
import 'update_organization_quota_command.dart';

/// Port for SuperAdmin information operations.
///
/// Concrete implementation: [SupabaseSuperAdminRepository].
/// Read methods are proxied through the `super-admin-proxy` Edge Function
/// (INV-3, INV-14). Write RPCs use the authenticated session JWT.
/// INV-4: Pure Dart interface — zero infrastructure dependencies.
abstract class ISuperAdminRepository {
  /// Atomically creates a new organization and records an 'ORG_CREATED' billing factEvent.
  ///
  /// Returns the new organization's UUID.
  Future<String> createOrganization(CreateOrganizationCommand command);

  /// Inserts an invitation for the org's first admin.
  ///
  /// IDs and token are generated by the caller (INV-7: Deterministic Replay).
  Future<void> inviteFirstAdmin({
    required String orgId,
    required String email,
    required String token,
    required String invitationId,
    required DateTime expiresAtUtc,
    required String superAdminUserId,
  });

  /// Checks whether a CNPJ (14 raw digits) already exists in the system.
  Future<bool> checkCnpjExists(String cnpjDigits);

  /// Reads all tenant health snapshots from `super_admin_tenant_health_view`.
  Future<List<TenantHealthSnapshot>> getAllTenantHealth();

  /// Reads system audit log entries, optionally filtered by organization.
  Future<List<SystemAuditLogEntry>> getSystemAuditLog({
    String? organizationId,
    String? severity,
    DateTime? fromDate,
    DateTime? toDate,
    int limit,
  });

  /// Updates an existing organization's plan type and quota limits.
  ///
  /// Atomically updates the organizations row and appends a 'PLAN_CHANGED'
  /// billing factEvent (INV-7). NULL limits = unlimited (enterprise tier).
  Future<void> updateOrganizationQuota(UpdateOrganizationQuotaCommand command);

  /// Archives an organization: sets status=ARCHIVED, revokes API secrets,
  /// appends ORG_ARCHIVED audit record.
  ///
  /// INV-3: Secrets revoked via revoked_at, never deleted.
  /// INV-26: Returns error for not-found AND wrong-org (404 parity).
  Future<void> archiveOrganization(ArchiveOrganizationCommand command);

  /// Unarchives an organization: sets status=ACTIVE, and unbans users.
  Future<void> unarchiveOrganization({
    required String orgId,
    required String reason,
    required String superAdminId,
  });

  /// Lists all members of a specific organization for SuperAdmin visibility.
  Future<List<Map<String, dynamic>>> getTenantMembers(String orgId);

  /// Toggles the active status of a tenant member.
  Future<void> toggleTenantMemberStatus({
    required String orgId,
    required String userId,
    required bool isActive,
  });

  /// Resends an invitation email to a tenant member.
  Future<void> resendInvitation({
    required String email,
    required String orgName,
  });
}
