// Mocks generated by Mockito 5.4.6 from annotations
// in veraprob/test/application/sla_audit/justification/security_defense_layers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:veraprob/application/shared/tenant_validation_service.dart'
    as _i5;
import 'package:veraprob/application/sla_audit/justification/contextual_signature_analyzer.dart'
    as _i13;
import 'package:veraprob/application/sla_audit/justification/evidence_integrity_verifier.dart'
    as _i11;
import 'package:veraprob/application/sla_audit/justification/evidence_validation_service.dart'
    as _i4;
import 'package:veraprob/application/sla_audit/justification/xss_input_sanitizer.dart'
    as _i2;
import 'package:veraprob/domain/shared/date_time_provider.dart' as _i10;
import 'package:veraprob/domain/enums/user_permissions.dart' as _i9;
import 'package:veraprob/domain/enums/user_role.dart' as _i8;
import 'package:veraprob/domain/services/rbac_service.dart' as _i7;
import 'package:veraprob/domain/sla_audit/justification/justification_audit_log.dart'
    as _i16;
import 'package:veraprob/domain/sla_audit/justification/justification_status.dart'
    as _i15;
import 'package:veraprob/domain/sla_audit/justification/sla_justification.dart'
    as _i3;
import 'package:veraprob/domain/sla_audit/justification/sla_justification_repository.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSanitizationResult_1 extends _i1.SmartFake
    implements _i2.SanitizationResult {
  _FakeSanitizationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSLAJustification_2 extends _i1.SmartFake
    implements _i3.SLAJustification {
  _FakeSLAJustification_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvidenceValidationResult_3 extends _i1.SmartFake
    implements _i4.EvidenceValidationResult {
  _FakeEvidenceValidationResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TenantValidationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantValidationService extends _i1.Mock
    implements _i5.TenantValidationService {
  MockTenantValidationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> assertTenantMatches({
    required String? payloadOrgId,
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assertTenantMatches, [], {
              #payloadOrgId: payloadOrgId,
              #sessionId: sessionId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void verifySourceOwnership({
    required String? resourceOrgId,
    required String? requesterOrgId,
    String? resourceType,
    String? resourceId,
  }) => super.noSuchMethod(
    Invocation.method(#verifySourceOwnership, [], {
      #resourceOrgId: resourceOrgId,
      #requesterOrgId: requesterOrgId,
      #resourceType: resourceType,
      #resourceId: resourceId,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RbacService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRbacService extends _i1.Mock implements _i7.RbacService {
  MockRbacService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool can(_i8.UserRole? role, _i9.UserPermission? permission) =>
      (super.noSuchMethod(
            Invocation.method(#can, [role, permission]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasMinimumRole(_i8.UserRole? role, _i8.UserRole? minimumRole) =>
      (super.noSuchMethod(
            Invocation.method(#hasMinimumRole, [role, minimumRole]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [IDateTimeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDateTimeProvider extends _i1.Mock implements _i10.IDateTimeProvider {
  MockIDateTimeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime nowUtc() =>
      (super.noSuchMethod(
            Invocation.method(#nowUtc, []),
            returnValue: _FakeDateTime_0(this, Invocation.method(#nowUtc, [])),
          )
          as DateTime);

  @override
  DateTime nowBrazil() =>
      (super.noSuchMethod(
            Invocation.method(#nowBrazil, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#nowBrazil, []),
            ),
          )
          as DateTime);
}

/// A class which mocks [EvidenceIntegrityVerifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvidenceIntegrityVerifier extends _i1.Mock
    implements _i11.EvidenceIntegrityVerifier {
  MockEvidenceIntegrityVerifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<int>> verifyAll({
    required List<String>? evidenceUrls,
    required List<String>? declaredHashes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAll, [], {
              #evidenceUrls: evidenceUrls,
              #declaredHashes: declaredHashes,
            }),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);
}

/// A class which mocks [XssInputSanitizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockXssInputSanitizer extends _i1.Mock implements _i2.XssInputSanitizer {
  MockXssInputSanitizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SanitizationResult sanitize(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#sanitize, [input]),
            returnValue: _FakeSanitizationResult_1(
              this,
              Invocation.method(#sanitize, [input]),
            ),
          )
          as _i2.SanitizationResult);

  @override
  String sanitizeText(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#sanitizeText, [input]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#sanitizeText, [input]),
            ),
          )
          as String);
}

/// A class which mocks [ContextualSignatureAnalyzer].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextualSignatureAnalyzer extends _i1.Mock
    implements _i13.ContextualSignatureAnalyzer {
  MockContextualSignatureAnalyzer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> validateEvidence(List<String>? urls) =>
      (super.noSuchMethod(
            Invocation.method(#validateEvidence, [urls]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> detectMimeType(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#detectMimeType, [url]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}

/// A class which mocks [SLAJustificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSLAJustificationRepository extends _i1.Mock
    implements _i14.SLAJustificationRepository {
  MockSLAJustificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.SLAJustification> create(
    _i3.SLAJustification? justification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [justification]),
            returnValue: _i6.Future<_i3.SLAJustification>.value(
              _FakeSLAJustification_2(
                this,
                Invocation.method(#create, [justification]),
              ),
            ),
          )
          as _i6.Future<_i3.SLAJustification>);

  @override
  _i6.Future<_i3.SLAJustification> createWithAuditLog({
    required _i3.SLAJustification? justification,
    required _i16.JustificationAuditLog? initialAuditLog,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWithAuditLog, [], {
              #justification: justification,
              #initialAuditLog: initialAuditLog,
            }),
            returnValue: _i6.Future<_i3.SLAJustification>.value(
              _FakeSLAJustification_2(
                this,
                Invocation.method(#createWithAuditLog, [], {
                  #justification: justification,
                  #initialAuditLog: initialAuditLog,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.SLAJustification>);

  @override
  _i6.Future<_i3.SLAJustification?> findById({
    required String? id,
    required String? organizationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [], {
              #id: id,
              #organizationId: organizationId,
            }),
            returnValue: _i6.Future<_i3.SLAJustification?>.value(),
          )
          as _i6.Future<_i3.SLAJustification?>);

  @override
  _i6.Future<_i3.SLAJustification?> findByVehicleAndEvent({
    required String? vehicleId,
    required DateTime? occurrenceTimestamp,
    required String? organizationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findByVehicleAndEvent, [], {
              #vehicleId: vehicleId,
              #occurrenceTimestamp: occurrenceTimestamp,
              #organizationId: organizationId,
            }),
            returnValue: _i6.Future<_i3.SLAJustification?>.value(),
          )
          as _i6.Future<_i3.SLAJustification?>);

  @override
  _i6.Future<_i3.SLAJustification> updateStatus({
    required String? id,
    required String? organizationId,
    required _i15.JustificationStatus? status,
    required String? reviewerId,
    required String? resolutionNotes,
    required DateTime? reviewedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [], {
              #id: id,
              #organizationId: organizationId,
              #status: status,
              #reviewerId: reviewerId,
              #resolutionNotes: resolutionNotes,
              #reviewedAtUtc: reviewedAtUtc,
            }),
            returnValue: _i6.Future<_i3.SLAJustification>.value(
              _FakeSLAJustification_2(
                this,
                Invocation.method(#updateStatus, [], {
                  #id: id,
                  #organizationId: organizationId,
                  #status: status,
                  #reviewerId: reviewerId,
                  #resolutionNotes: resolutionNotes,
                  #reviewedAtUtc: reviewedAtUtc,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.SLAJustification>);

  @override
  _i6.Future<List<_i3.SLAJustification>> findExpiredPlanned({
    required DateTime? cutoffUtc,
    required String? organizationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExpiredPlanned, [], {
              #cutoffUtc: cutoffUtc,
              #organizationId: organizationId,
            }),
            returnValue: _i6.Future<List<_i3.SLAJustification>>.value(
              <_i3.SLAJustification>[],
            ),
          )
          as _i6.Future<List<_i3.SLAJustification>>);

  @override
  _i6.Future<List<_i3.SLAJustification>> findExpiredPendingPaged({
    required DateTime? cutoffUtc,
    required String? organizationId,
    required int? limit,
    String? afterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExpiredPendingPaged, [], {
              #cutoffUtc: cutoffUtc,
              #organizationId: organizationId,
              #limit: limit,
              #afterId: afterId,
            }),
            returnValue: _i6.Future<List<_i3.SLAJustification>>.value(
              <_i3.SLAJustification>[],
            ),
          )
          as _i6.Future<List<_i3.SLAJustification>>);

  @override
  _i6.Future<int> updateStatusAtomic({
    required String? id,
    required String? organizationId,
    required _i15.JustificationStatus? expectedCurrentStatus,
    required _i15.JustificationStatus? newStatus,
    required String? reviewerId,
    required String? resolutionNotes,
    required DateTime? reviewedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatusAtomic, [], {
              #id: id,
              #organizationId: organizationId,
              #expectedCurrentStatus: expectedCurrentStatus,
              #newStatus: newStatus,
              #reviewerId: reviewerId,
              #resolutionNotes: resolutionNotes,
              #reviewedAtUtc: reviewedAtUtc,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> appendAuditLog(_i16.JustificationAuditLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#appendAuditLog, [log]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> updateStatusWithAuditLog({
    required String? id,
    required String? organizationId,
    required _i15.JustificationStatus? expectedCurrentStatus,
    required _i15.JustificationStatus? newStatus,
    required String? reviewerId,
    required String? resolutionNotes,
    required DateTime? reviewedAtUtc,
    required String? callerRole,
    required List<String>? evidenceUrls,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatusWithAuditLog, [], {
              #id: id,
              #organizationId: organizationId,
              #expectedCurrentStatus: expectedCurrentStatus,
              #newStatus: newStatus,
              #reviewerId: reviewerId,
              #resolutionNotes: resolutionNotes,
              #reviewedAtUtc: reviewedAtUtc,
              #callerRole: callerRole,
              #evidenceUrls: evidenceUrls,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [EvidenceLinkChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvidenceLinkChecker extends _i1.Mock
    implements _i4.EvidenceLinkChecker {
  MockEvidenceLinkChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.EvidenceValidationResult> checkLink(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#checkLink, [url]),
            returnValue: _i6.Future<_i4.EvidenceValidationResult>.value(
              _FakeEvidenceValidationResult_3(
                this,
                Invocation.method(#checkLink, [url]),
              ),
            ),
          )
          as _i6.Future<_i4.EvidenceValidationResult>);
}
