import 'package:equatable/equatable.dart';
import 'package:timezone/timezone.dart' as tz;

import 'domain_exception.dart';
import 'sla_penalties.dart';

/// Days of the week, aligned with Dart's [DateTime.weekday] constants.
/// Monday = 1, Sunday = 7.
enum DayOfWeek {
  monday(1),
  tuesday(2),
  wednesday(3),
  thursday(4),
  friday(5),
  saturday(6),
  sunday(7);

  final int value;
  const DayOfWeek(this.value);

  static DayOfWeek fromValue(int v) =>
      DayOfWeek.values.firstWhere((d) => d.value == v);
}

/// Value object representing a recurrence rule for a contractual service.
///
/// **ADR — UTC Invariant Exception:**
/// Unlike all other temporal data in the domain (which is stored in UTC),
/// [ShiftPattern] stores local time ([arrivalTimeLocal], [departureTimeLocal])
/// plus an IANA timezone identifier ([timezone]). This is a documented
/// exception because recurrence rules cannot be expressed in absolute UTC:
/// "arrive at 07:00 every weekday" is a local-time concept.
///
/// Conversion to UTC occurs in [ShiftProjectionService] at projection time,
/// not in this domain object. See `docs/governance/roadmap.md` — Invariantes.
///
/// **Equality** is based on all fields (value object — no identity).
class ShiftPattern extends Equatable {
  /// Zero-based index within the parent [PlanDeclaration.shiftPatterns] list.
  /// Used as part of the deterministic SET id: SHA-256(planId + index + date).
  final int index;

  /// Days of the week this shift runs.
  final List<DayOfWeek> daysOfWeek;

  /// Local time at which the vehicle must arrive at the destination geofence.
  /// Format: "HH:mm" (24-hour). Converted to UTC by [ShiftProjectionService].
  final String arrivalTimeLocal;

  /// Local time at which the vehicle departs from the origin geofence.
  /// Format: "HH:mm" (24-hour). Must be before [arrivalTimeLocal] on the same day.
  final String departureTimeLocal;

  /// IANA timezone identifier (e.g. "America/Sao_Paulo").
  /// Validated against the timezone database at creation time.
  final String timezone;

  /// ID of the origin [OperationalZone]. Resolved to coordinates at projection time.
  final String originZoneId;

  /// ID of the destination [OperationalZone]. Resolved to coordinates at projection time.
  final String destinationZoneId;

  /// SLA penalty rules that apply to SETs generated by this pattern.
  final SLAPenalties penalties;

  const ShiftPattern._({
    required this.index,
    required this.daysOfWeek,
    required this.arrivalTimeLocal,
    required this.departureTimeLocal,
    required this.timezone,
    required this.originZoneId,
    required this.destinationZoneId,
    required this.penalties,
  });

  /// Creates a [ShiftPattern] with validated invariants.
  ///
  /// Validates timezone against IANA database, time format, and business rules.
  /// Throws [DomainException] if any invariant is violated.
  factory ShiftPattern.create({
    required int index,
    required List<DayOfWeek> daysOfWeek,
    required String arrivalTimeLocal,
    required String departureTimeLocal,
    required String timezone,
    required String originZoneId,
    required String destinationZoneId,
    required SLAPenalties penalties,
  }) {
    if (index < 0) {
      throw const DomainException('ShiftPattern index must be >= 0');
    }
    if (daysOfWeek.isEmpty) {
      throw const DomainException('daysOfWeek must not be empty');
    }
    if (originZoneId.isEmpty) {
      throw const DomainException('originZoneId must not be empty');
    }
    if (destinationZoneId.isEmpty) {
      throw const DomainException('destinationZoneId must not be empty');
    }

    _validateTimeFormat(arrivalTimeLocal, 'arrivalTimeLocal');
    _validateTimeFormat(departureTimeLocal, 'departureTimeLocal');
    _validateTimezone(timezone);

    // Departure must be before arrival on the same operational day
    final dep = _parseTime(departureTimeLocal);
    final arr = _parseTime(arrivalTimeLocal);
    if (!dep.isBefore(arr)) {
      throw const DomainException(
        'departureTimeLocal must be before arrivalTimeLocal',
      );
    }

    return ShiftPattern._(
      index: index,
      daysOfWeek: List.unmodifiable(daysOfWeek),
      arrivalTimeLocal: arrivalTimeLocal,
      departureTimeLocal: departureTimeLocal,
      timezone: timezone,
      originZoneId: originZoneId,
      destinationZoneId: destinationZoneId,
      penalties: penalties,
    );
  }

  /// Reconstitutes from persistence without re-validating invariants.
  factory ShiftPattern.reconstitute({
    required int index,
    required List<DayOfWeek> daysOfWeek,
    required String arrivalTimeLocal,
    required String departureTimeLocal,
    required String timezone,
    required String originZoneId,
    required String destinationZoneId,
    required SLAPenalties penalties,
  }) {
    return ShiftPattern._(
      index: index,
      daysOfWeek: List.unmodifiable(daysOfWeek),
      arrivalTimeLocal: arrivalTimeLocal,
      departureTimeLocal: departureTimeLocal,
      timezone: timezone,
      originZoneId: originZoneId,
      destinationZoneId: destinationZoneId,
      penalties: penalties,
    );
  }

  /// Returns true if this pattern runs on [weekday] (1 = Monday, 7 = Sunday).
  bool runsOn(int weekday) => daysOfWeek.any((d) => d.value == weekday);

  /// Serializes to JSON for JSONB storage in [plan_declarations.shift_patterns_payload].
  Map<String, dynamic> toJson() => {
        'index': index,
        'daysOfWeek': daysOfWeek.map((d) => d.value).toList(),
        'arrivalTimeLocal': arrivalTimeLocal,
        'departureTimeLocal': departureTimeLocal,
        'timezone': timezone,
        'originZoneId': originZoneId,
        'destinationZoneId': destinationZoneId,
        'penalties': penalties.toJson(),
      };

  factory ShiftPattern.fromJson(Map<String, dynamic> json) {
    final days = (json['daysOfWeek'] as List<dynamic>)
        .map((v) => DayOfWeek.fromValue(v as int))
        .toList();

    return ShiftPattern._(
      index: json['index'] as int,
      daysOfWeek: List.unmodifiable(days),
      arrivalTimeLocal: json['arrivalTimeLocal'] as String,
      departureTimeLocal: json['departureTimeLocal'] as String,
      timezone: json['timezone'] as String,
      originZoneId: json['originZoneId'] as String,
      destinationZoneId: json['destinationZoneId'] as String,
      penalties: SLAPenalties.fromJson(
        Map<String, dynamic>.from(json['penalties'] as Map),
      ),
    );
  }

  // ── Private helpers ──────────────────────────────────────

  static void _validateTimeFormat(String time, String fieldName) {
    final parts = time.split(':');
    if (parts.length != 2) {
      throw DomainException('$fieldName must be in HH:mm format');
    }
    final hour = int.tryParse(parts[0]);
    final minute = int.tryParse(parts[1]);
    if (hour == null || minute == null || hour < 0 || hour > 23 ||
        minute < 0 || minute > 59) {
      throw DomainException('$fieldName has invalid time value: $time');
    }
  }

  /// Validates timezone against the IANA timezone database.
  /// Throws [DomainException] for unknown timezone identifiers.
  static void _validateTimezone(String timezone) {
    if (timezone.isEmpty) {
      throw const DomainException('timezone must not be empty');
    }
    try {
      tz.getLocation(timezone);
    } catch (_) {
      throw DomainException(
        'Unknown timezone: "$timezone". Must be a valid IANA timezone identifier '
        '(e.g. "America/Sao_Paulo").',
      );
    }
  }

  /// Parses "HH:mm" into a comparable [DateTime] on an arbitrary fixed date.
  static DateTime _parseTime(String time) {
    final parts = time.split(':');
    return DateTime(2000, 1, 1, int.parse(parts[0]), int.parse(parts[1]));
  }

  @override
  List<Object?> get props => [
        index,
        daysOfWeek,
        arrivalTimeLocal,
        departureTimeLocal,
        timezone,
        originZoneId,
        destinationZoneId,
        penalties,
      ];
}
