import 'package:equatable/equatable.dart';

/// The ultimate forensic asset for SLA Audit.
///
/// Represents an immutable historical fact that occurred in the SLA domain.
/// Unlike [DomainEvent], this is designed for long-term forensic storage
/// and is mapped from application-layer decisions.
class SlaLedgerEntry extends Equatable {
  /// Monotonic sequence ID from the database.
  /// Null if not yet persisted.
  final int? id;

  /// UUID primary key from sla_audit_ledger_v2.
  /// Generated by the database on insert. Used for causal linkage
  /// with evaluation traces.
  final String? eventId;

  /// Forensic type of the entry (e.g., 'PLAN_DECLARED', 'EXECUTION_BOUND').
  final String type;

  /// The Tenant / Organization ID that owns this ledger entry.
  final String organizationId;

  /// The ID of the operator (user or system) that triggered this entry.
  final String operatorId;

  /// Causal linkage: The specific obligation (SET) this entry refers to.
  /// For plan-level events, this might be null or represent the whole declaration.
  final String? setId;

  /// Causal linkage: The contract this obligation belongs to.
  final String contractId;

  /// Causal linkage: The specific version of the plan declaration.
  final int planVersion;

  /// The timestamp in UTC when the fact occurred.
  final DateTime occurredAtUtc;

  /// Complementary forensic information in a structured but flexible format.
  final Map<String, dynamic> payload;

  const SlaLedgerEntry({
    this.id,
    this.eventId,
    required this.organizationId,
    required this.type,
    this.operatorId = 'SYSTEM',
    this.setId,
    required this.contractId,
    required this.planVersion,
    required this.occurredAtUtc,
    this.payload = const {},
  });

  @override
  List<Object?> get props => [
    id,
    eventId,
    organizationId,
    type,
    operatorId,
    setId,
    contractId,
    planVersion,
    occurredAtUtc,
    payload,
  ];
}
