import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:equatable/equatable.dart';

import '../shared/money.dart';
import 'domain_exception.dart';

/// Value Object: forensic evidence bundle that justifies a penalty verdict.
///
/// Satisfies **INV-23** — every penalty generated by the engine MUST include
/// a reference to the specific rule version and the primary evidence
/// (GPS/Timestamp) that triggered it.
///
/// [evidenceHash] = SHA-256 of the canonical serialized bundle.
/// Deterministic: same inputs → same hash (INV-7).
///
/// **Invariants enforced:**
/// - INV-2: [fineCents] stored as integer cents via [Money] VO.
/// - INV-3: [primaryEvidenceTimestampUtc] must be UTC.
/// - INV-4: zero Flutter/Supabase dependencies.
class VerdictEvidence extends Equatable {
  final String clauseRef;
  final String ruleId;
  final int ruleVersion;
  final double primaryEvidenceLat;
  final double primaryEvidenceLng;
  final DateTime primaryEvidenceTimestampUtc;

  /// SHA-256 of the canonical bundle. Deterministic for the same input.
  final String evidenceHash;

  /// How far past the threshold the violation went (e.g., minutes late).
  final double deltaValue;

  /// The contractual threshold that was breached (e.g., 0 minutes over).
  final double thresholdValue;

  /// Penalty amount in cents (INV-2). Always > 0.
  final Money fineCents;

  /// Engine confidence in the verdict, 0-100. 100 = deterministic sweep.
  final int confidenceScore;

  const VerdictEvidence._({
    required this.clauseRef,
    required this.ruleId,
    required this.ruleVersion,
    required this.primaryEvidenceLat,
    required this.primaryEvidenceLng,
    required this.primaryEvidenceTimestampUtc,
    required this.evidenceHash,
    required this.deltaValue,
    required this.thresholdValue,
    required this.fineCents,
    required this.confidenceScore,
  });

  /// Creates a new [VerdictEvidence], computing [evidenceHash] from the bundle.
  ///
  /// Throws [DomainException] if any field invariant is violated.
  factory VerdictEvidence.create({
    required String clauseRef,
    required String ruleId,
    required int ruleVersion,
    required double primaryEvidenceLat,
    required double primaryEvidenceLng,
    required DateTime primaryEvidenceTimestampUtc,
    required double deltaValue,
    required double thresholdValue,
    required Money fineCents,
    required int confidenceScore,
  }) {
    if (clauseRef.isEmpty) {
      throw const DomainException('clauseRef must not be empty');
    }
    if (ruleId.isEmpty) {
      throw const DomainException('ruleId must not be empty');
    }
    if (primaryEvidenceLat < -90 || primaryEvidenceLat > 90) {
      throw const DomainException(
        'primaryEvidenceLat must be between -90 and 90',
      );
    }
    if (primaryEvidenceLng < -180 || primaryEvidenceLng > 180) {
      throw const DomainException(
        'primaryEvidenceLng must be between -180 and 180',
      );
    }
    if (!primaryEvidenceTimestampUtc.isUtc) {
      throw const DomainException(
        'primaryEvidenceTimestampUtc must be UTC (INV-3). Call .toUtc() before passing.',
      );
    }
    if (fineCents.cents <= 0) {
      throw const DomainException('fineCents must be > 0 (INV-2)');
    }
    if (confidenceScore < 0 || confidenceScore > 100) {
      throw const DomainException(
        'confidenceScore must be between 0 and 100',
      );
    }

    final evidenceHash = _computeHash(
      clauseRef: clauseRef,
      ruleId: ruleId,
      ruleVersion: ruleVersion,
      lat: primaryEvidenceLat,
      lng: primaryEvidenceLng,
      timestampUtc: primaryEvidenceTimestampUtc,
      deltaValue: deltaValue,
      thresholdValue: thresholdValue,
      fineCents: fineCents.cents,
    );

    return VerdictEvidence._(
      clauseRef: clauseRef,
      ruleId: ruleId,
      ruleVersion: ruleVersion,
      primaryEvidenceLat: primaryEvidenceLat,
      primaryEvidenceLng: primaryEvidenceLng,
      primaryEvidenceTimestampUtc: primaryEvidenceTimestampUtc,
      evidenceHash: evidenceHash,
      deltaValue: deltaValue,
      thresholdValue: thresholdValue,
      fineCents: fineCents,
      confidenceScore: confidenceScore,
    );
  }

  /// Reconstitutes from persistence. Does NOT recompute hash — trusts stored value.
  factory VerdictEvidence.fromJson(Map<String, dynamic> json) {
    return VerdictEvidence._(
      clauseRef: json['clause_ref'] as String,
      ruleId: json['rule_id'] as String,
      ruleVersion: json['rule_version'] as int,
      primaryEvidenceLat: (json['primary_evidence_lat'] as num).toDouble(),
      primaryEvidenceLng: (json['primary_evidence_lng'] as num).toDouble(),
      primaryEvidenceTimestampUtc: DateTime.parse(
        json['primary_evidence_timestamp_utc'] as String,
      ),
      evidenceHash: json['evidence_hash'] as String,
      deltaValue: (json['delta_value'] as num).toDouble(),
      thresholdValue: (json['threshold_value'] as num).toDouble(),
      fineCents: Money(json['fine_cents'] as int),
      confidenceScore: json['confidence_score'] as int,
    );
  }

  Map<String, dynamic> toJson() => {
    'clause_ref': clauseRef,
    'rule_id': ruleId,
    'rule_version': ruleVersion,
    'primary_evidence_lat': primaryEvidenceLat,
    'primary_evidence_lng': primaryEvidenceLng,
    'primary_evidence_timestamp_utc':
        primaryEvidenceTimestampUtc.toIso8601String(),
    'evidence_hash': evidenceHash,
    'delta_value': deltaValue,
    'threshold_value': thresholdValue,
    'fine_cents': fineCents.cents,
    'confidence_score': confidenceScore,
  };

  // ── Private hash helpers ──────────────────────────────────────────────────

  /// Canonical payload for evidence hashing. Field order is fixed — do not change.
  static String _computeHash({
    required String clauseRef,
    required String ruleId,
    required int ruleVersion,
    required double lat,
    required double lng,
    required DateTime timestampUtc,
    required double deltaValue,
    required double thresholdValue,
    required int fineCents,
  }) {
    final canonical = {
      'clause_ref': clauseRef,
      'rule_id': ruleId,
      'rule_version': ruleVersion,
      'primary_evidence_lat': lat,
      'primary_evidence_lng': lng,
      'primary_evidence_timestamp_utc': timestampUtc.toIso8601String(),
      'delta_value': deltaValue,
      'threshold_value': thresholdValue,
      'fine_cents': fineCents,
    };
    return sha256.convert(utf8.encode(jsonEncode(canonical))).toString();
  }

  @override
  List<Object?> get props => [evidenceHash];
}
