import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/driver.dart';
import 'driver_repository.dart';

class DriverRepositoryImpl implements IDriverRepository {
  final SupabaseClient _supabase;

  DriverRepositoryImpl(this._supabase);

  @override
  Future<List<Driver>> getDrivers() async {
    final response = await _supabase
        .from('drivers')
        .select()
        .order('full_name', ascending: true);

    return (response as List).map((data) {
      return Driver(
        id: data['id'],
        name: data['full_name'],
        licenseNumber: data['license_number'],
      );
    }).toList();
  }

  @override
  Future<void> addDriver(Driver driver) async {
    await _supabase.from('drivers').insert({
      'full_name': driver.name,
      'license_number': driver.licenseNumber,
      // 'id' is generated by DB default uuid_generate_v4()
    });
  }

  @override
  Future<void> deleteDriver(String driverId) async {
    await _supabase.from('drivers').delete().eq('id', driverId);
  }

  @override
  Future<void> updateDriver(Driver driver) async {
    await _supabase
        .from('drivers')
        .update({
          'full_name': driver.name,
          'license_number': driver.licenseNumber,
        })
        .eq('id', driver.id);
  }
}
