import 'package:veraprob/domain/entities/operational_trip.dart';
import 'package:veraprob/domain/entities/operational_warning.dart';
import 'package:veraprob/domain/entities/trip_event.dart';
import 'package:veraprob/domain/enums/trip_status.dart';
import 'package:veraprob/application/normalization/models/vehicle_operational_state.dart';
import 'package:veraprob/application/normalization/models/motion_state.dart';
import 'situation_detector.dart';

/// Detects if a dispatched/enRoute vehicle is stopped for too long.
///
/// Rule:
/// - In Phase 1 we use the real [MotionState] generated by the Normalization Layer.
/// - If state is [MotionState.stopped] (and NOT [MotionState.dwellingAtStop]),
///   we flag it as a severe stoppage.
/// - We still keep the fallback for interrupted trips from Phase 0.
class StoppedVehicleDetector extends SituationDetector {
  StoppedVehicleDetector(super.dateTimeProvider)
    : super(id: 'stopped_vehicle', name: 'Detector de Veículo Parado');

  @override
  bool canDetect(OperationalTrip trip) {
    return trip.isActive;
  }

  @override
  OperationalWarning? evaluate(
    OperationalTrip trip,
    VehicleOperationalState? state,
    List<TripEvent> history,
  ) {
    // 1. Check real operational state from the Normalization Layer
    if (state != null && state.motionState == MotionState.stopped) {
      final nowUtc = dateTimeProvider.nowUtc();
      final minutesStopped = nowUtc.difference(state.stateChangedAt).inMinutes;
      // Only warn if stopped for a significant time based on business logic
      // (The normalizer already requires 15s to classify as stopped, but for a severe warning we might want more like 2-3 mins)
      if (minutesStopped >= 2) {
        return OperationalWarning(
          id: 'warn_stopped_operational_${trip.id}',
          type: 'vehicle_stopped',
          message: 'Veículo Parado na Via: $minutesStopped min',
          severityScore: 40,
          detectedAt: state.lastRawPingAt,
        );
      }
    }

    // 2. Fallback heuristic: if the trip is interrupted manually
    if (trip.status == TripStatus.interrupted) {
      return OperationalWarning(
        id: 'warn_stopped_interrupted_${trip.id}',
        type: 'vehicle_stopped',
        message: 'Veículo Interrompido',
        severityScore: 50,
        detectedAt: state?.lastRawPingAt ?? dateTimeProvider.nowUtc(),
      );
    }

    return null;
  }
}
