// Unit tests for PdfDossierGenerator.
//
// Validates that the generated PDF bytes are structurally valid and contain
// the required SHA-256 chain-of-custody hash (INV-9) and UTC timestamps (INV-6).
//
// NOTE: These are pure unit tests — no network or DB required.

import 'package:flutter_test/flutter_test.dart';
import 'package:veraprob/domain/reporting/forensic_dossier.dart';
import 'package:veraprob/domain/reporting/i_forensic_pdf_generator.dart';
import 'package:veraprob/domain/sla_audit/sla_ledger_entry.dart';
import 'package:veraprob/infrastructure/reporting/pdf_dossier_generator.dart';

// ── Helpers ───────────────────────────────────────────────────────────────────

SlaLedgerEntry _buildEntry({
  String eventId = 'event-pdf-test-001',
  String organizationId = 'org-test',
  String contractId = 'contract-pdf-test',
}) => SlaLedgerEntry(
  eventId: eventId,
  organizationId: organizationId,
  contractId: contractId,
  type: 'SANCTION_VERDICT',
  planVersion: 1,
  occurredAtUtc: DateTime.utc(2026, 3, 15, 10, 30, 0),
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  group('PdfDossierGenerator', () {
    late PdfDossierGenerator generator;

    setUp(() {
      generator = PdfDossierGenerator();
    });

    // ── Structural Validity ───────────────────────────────────────────────────

    group('DossierClassification matrix (4-color watermark)', () {
      test('preliminary produces PRELIMINAR - EM ANÁLISE watermark', () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 0,
          classification: DossierClassification.preliminary,
        );
        final bytes = await generator.generateDossier(dossier);
        final text = String.fromCharCodes(
          bytes.where((b) => b >= 32 && b < 127),
        );
        expect(text, contains('PRELIMINAR'));
      });

      test('applied produces INFRAÇÃO CONFIRMADA watermark', () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 0,
          classification: DossierClassification.applied,
        );
        final bytes = await generator.generateDossier(dossier);
        final text = String.fromCharCodes(
          bytes.where((b) => b >= 32 && b < 127),
        );
        expect(text, contains('CONFIRMADA'));
      });

      test('annulled produces INFRAÇÃO ANULADA watermark', () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 0,
          classification: DossierClassification.annulled,
        );
        final bytes = await generator.generateDossier(dossier);
        final text = String.fromCharCodes(
          bytes.where((b) => b >= 32 && b < 127),
        );
        expect(text, contains('ANULADA'));
      });

      test(
        'acknowledged produces VEREDITO SELADO - DE ACORDO watermark',
        () async {
          final dossier = ForensicDossier(
            ledgerEntry: _buildEntry(),
            mapImageBytes: const [],
            savingsCents: 0,
            classification: DossierClassification.acknowledged,
          );
          final bytes = await generator.generateDossier(dossier);
          // Let's check for VEREDITO, SELADO and ACORDO.
          final text = String.fromCharCodes(
            bytes.where((b) => b >= 32 && b < 127),
          );
          expect(text, contains('VEREDITO'));
          expect(text, contains('SELADO'));
          expect(text, contains('ACORDO'));
        },
      );
    });

    test('generateDossier returns non-empty bytes', () async {
      final dossier = ForensicDossier(
        ledgerEntry: _buildEntry(),
        mapImageBytes: const [],
        savingsCents: 100000,
      );

      final bytes = await generator.generateDossier(dossier);

      expect(bytes, isNotEmpty);
    });

    test('generated bytes start with PDF magic header (%PDF)', () async {
      final dossier = ForensicDossier(
        ledgerEntry: _buildEntry(),
        mapImageBytes: const [],
        savingsCents: 0,
      );

      final bytes = await generator.generateDossier(dossier);

      // PDF magic: 0x25 0x50 0x44 0x46 = '%PDF'
      expect(bytes[0], equals(0x25));
      expect(bytes[1], equals(0x50));
      expect(bytes[2], equals(0x44));
      expect(bytes[3], equals(0x46));
    });

    // ── INV-9: SHA-256 Chain of Custody ──────────────────────────────────────

    test('generated PDF content contains SHA-256 hash (INV-9)', () async {
      final dossier = ForensicDossier(
        ledgerEntry: _buildEntry(),
        mapImageBytes: const [1, 2, 3, 4, 5],
        savingsCents: 250000,
      );

      final expectedHash = dossier.computeHash();
      final bytes = await generator.generateDossier(dossier);

      // SHA-256 is a 64-char hex string — must appear verbatim in PDF bytes.
      final pdfText = String.fromCharCodes(
        bytes.where((b) => b >= 32 && b < 127),
      );
      expect(
        pdfText.contains(expectedHash),
        isTrue,
        reason:
            'INV-9: SHA-256 hash must be embedded in the PDF footer. '
            'Hash: $expectedHash',
      );
    });

    test(
      'hash is deterministic — same input produces same PDF hash (INV-9)',
      () async {
        final entry = _buildEntry();
        const mapBytes = [10, 20, 30];

        final dossier1 = ForensicDossier(
          ledgerEntry: entry,
          mapImageBytes: mapBytes,
          savingsCents: 500000,
        );
        final dossier2 = ForensicDossier(
          ledgerEntry: entry,
          mapImageBytes: mapBytes,
          savingsCents: 500000,
        );

        final hash1 = dossier1.computeHash();
        final hash2 = dossier2.computeHash();

        expect(hash1, equals(hash2));

        // Both PDFs must embed the same deterministic hash.
        final bytes1 = await generator.generateDossier(dossier1);
        final bytes2 = await generator.generateDossier(dossier2);
        final text1 = String.fromCharCodes(
          bytes1.where((b) => b >= 32 && b < 127),
        );
        final text2 = String.fromCharCodes(
          bytes2.where((b) => b >= 32 && b < 127),
        );

        expect(text1.contains(hash1), isTrue);
        expect(text2.contains(hash2), isTrue);
      },
    );

    // ── INV-6: UTC Timestamps ─────────────────────────────────────────────────

    test('generated PDF contains UTC timestamp label (INV-6)', () async {
      final dossier = ForensicDossier(
        ledgerEntry: _buildEntry(),
        mapImageBytes: const [],
        savingsCents: 0,
      );

      final bytes = await generator.generateDossier(dossier);
      final pdfText = String.fromCharCodes(
        bytes.where((b) => b >= 32 && b < 127),
      );

      expect(
        pdfText.contains('UTC'),
        isTrue,
        reason: 'INV-6: PDF must contain UTC label on timestamps.',
      );
    });

    // ── Edge Cases ────────────────────────────────────────────────────────────

    test(
      'generateDossier handles empty mapImageBytes (N/D fallback)',
      () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 0,
        );

        // Must not throw — N/D fallback renders text instead of image.
        final bytes = await generator.generateDossier(dossier);
        expect(bytes, isNotEmpty);
      },
    );

    test(
      'generateDossier handles null telegramImageBytes (optional evidence)',
      () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [1, 2],
          // telegramImageBytes is null (optional)
          savingsCents: 5000,
        );

        final bytes = await generator.generateDossier(dossier);
        expect(bytes, isNotEmpty);
      },
    );

    test(
      'generateDossier wraps unexpected errors in PdfGenerationException',
      () async {
        // PdfGenerationException is the declared exception type for this port.
        // Verify it has DomainException semantics.
        const ex = PdfGenerationException('test error');
        expect(ex.message, equals('test error'));
      },
    );

    // ── Pkg 1: Financial correctness & legal hardening ───────────────────────
    // Regression guards for the annulment billing bug + legal footer + doc id +
    // contextual empty-section text. Accented glyphs do not survive the
    // 32..126 byte filter, so all assertions use ASCII substrings only.

    String pdfTextOf(List<int> bytes) =>
        String.fromCharCodes(bytes.where((b) => b >= 32 && b < 127));

    group('financial summary (annulment billing bug)', () {
      test('annulled dossier renders R\$ 0,00 impact + original amount marked '
          'isentada (carrier never re-billed off an annulment)', () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 150000, // R$ 1500,00 original fine
          classification: DossierClassification.annulled,
        );

        // PDF content streams emit one [(token)]TJ per word, so assert on
        // single space-free tokens, never multi-word phrases.
        final text = pdfTextOf(await generator.generateDossier(dossier));

        expect(text, contains('0,00'));
        expect(text, contains('isentada'));
        // Original amount stays visible as context, never as the impact value.
        expect(text, contains('1500.00'));
      });

      test(
        'applied dossier renders the full financial impact (no isentada note)',
        () async {
          final dossier = ForensicDossier(
            ledgerEntry: _buildEntry(),
            mapImageBytes: const [],
            savingsCents: 150000,
            classification: DossierClassification.applied,
          );

          final text = pdfTextOf(await generator.generateDossier(dossier));

          expect(text, contains('1500.00'));
          expect(text, isNot(contains('isentada')));
        },
      );
    });

    test('footer carries the legal validity disclaimer', () async {
      final dossier = ForensicDossier(
        ledgerEntry: _buildEntry(),
        mapImageBytes: const [],
        savingsCents: 0,
      );

      final text = pdfTextOf(await generator.generateDossier(dossier));

      // Single token from "Dispensada assinatura manual".
      expect(text, contains('Dispensada'));
    });

    test(
      'header carries a citable document id (Dossiê Nº = eventId)',
      () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(eventId: 'event-pdf-test-042'),
          mapImageBytes: const [],
          savingsCents: 0,
        );

        final text = pdfTextOf(await generator.generateDossier(dossier));

        expect(text, contains('event-pdf-test-042'));
      },
    );

    test(
      'empty map renders contextual fallback text, never a bare N/D',
      () async {
        final dossier = ForensicDossier(
          ledgerEntry: _buildEntry(),
          mapImageBytes: const [],
          savingsCents: 0,
        );

        final text = pdfTextOf(await generator.generateDossier(dossier));

        // Single token from "Sem coordenadas registradas para esta ocorrência."
        expect(text, contains('coordenadas'));
      },
    );
  });
}
