import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:veraprob/infrastructure/shared/postgres_error_interceptor.dart';

/// INV-26: Base repository for all Postgres-backed implementations.
///
/// Provides:
/// - [PostgresErrorInterceptor] mixin for automatic error translation
/// - Standard try/catch pattern for Supabase calls
/// - Forensic payload hashing for INSERT operations with DB-generated IDs
///
/// Usage:
/// ```dart
/// class MyRepository extends BasePostgresRepository implements IMyRepository {
///   Future<MyEntity?> findById(String id) async {
///     return withErrorHandler(
///       'my_entity',
///       id,
///       () async {
///         final data = await client.from('my_table').select().eq('id', id).maybeSingle();
///         if (data == null) return null;
///         return _mapToEntity(data);
///       },
///     );
///   }
///
///   Future<void> insert(MyEntity entity, Map<String, dynamic> payload) async {
///     return withErrorHandler(
///       'my_entity',
///       null,  // ID not yet known — generated by DB
///       () async { await client.from('my_table').insert(payload); },
///       insertPayload: payload,  // ← SHA-256 hash for forensic traceability
///     );
///   }
/// }
/// ```
abstract class BasePostgresRepository with PostgresErrorInterceptor {
  final SupabaseClient client;

  BasePostgresRepository(this.client);

  /// Executes a Supabase operation with automatic PostgREST error handling.
  ///
  /// [resourceType] — domain name of the resource (e.g., 'contract').
  /// [resourceId] — entity ID if known (Dart-generated UUID). If null (DB-generated ID),
  ///   the [insertPayload] will be SHA-256 hashed to provide forensic traceability.
  /// [operation] — the Supabase call to execute.
  /// [insertPayload] — optional raw payload for INSERT operations. Used to generate
  ///   a forensic hash when [resourceId] is null.
  ///
  /// On [PostgrestException], the error is translated to a domain exception
  /// with full forensic metadata — never leaks raw DB error codes to the caller (INV-26).
  Future<T> withErrorHandler<T>(
    String resourceType,
    String? resourceId,
    Future<T> Function() operation, {
    Map<String, dynamic>? insertPayload,
  }) async {
    try {
      return await operation();
    } on PostgrestException catch (e) {
      // INV-26 + SOC Correlation: If resourceId is null (DB-generated ID),
      // generate a SHA-256 hash of the insert payload so the SOC can correlate
      // the failure to a specific payload, even without a UUID.
      final forensicResourceId =
          resourceId ?? _hashPayloadIfPresent(insertPayload);

      throw mapPostgrestToDomainException(
        e,
        resourceType: resourceType,
        resourceId: forensicResourceId,
      );
    }
  }

  /// Generates a SHA-256 hex digest of a JSON payload for forensic traceability.
  ///
  /// Returns null if payload is null or empty.
  /// The hash allows the SOC to correlate a failure to a specific payload even
  /// when the database-generated ID is not yet known.
  ///
  /// **INV-15 (Deterministic):** Keys are sorted alphabetically before encoding
  /// to ensure canonical JSON — identical to the Deno `sortKeys()` function used
  /// by the HMAC verification worker. Without this, Dart's `jsonEncode` preserves
  /// Map insertion order, which would produce different hashes than the Deno side.
  static String? _hashPayloadIfPresent(Map<String, dynamic>? payload) {
    if (payload == null || payload.isEmpty) return null;
    final canonicalJson = jsonEncode(_sortKeys(payload));
    return sha256.convert(utf8.encode(canonicalJson)).toString();
  }

  /// Recursively sorts Map keys alphabetically for canonical JSON serialization.
  ///
  /// Dart's `jsonEncode` preserves Map insertion order. To ensure identical hashes
  /// between Dart (insert) and Deno (verification), keys MUST be sorted
  /// alphabetically — matching the Deno `sortKeys()` function in `hmac_signer.ts`.
  static dynamic _sortKeys(dynamic obj) {
    if (obj == null || obj is! Map<String, dynamic>) return obj;
    final sorted = <String, dynamic>{};
    final keys = obj.keys.toList()..sort();
    for (final key in keys) {
      sorted[key] = _sortKeys(obj[key]);
    }
    return sorted;
  }
}
