import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:veraprob/domain/shared/conflict_exception.dart';
import 'package:veraprob/infrastructure/shared/postgres_error_interceptor.dart';

/// INV-26: Base repository for all Postgres-backed implementations.
///
/// Provides:
/// - [PostgresErrorInterceptor] mixin for automatic error translation
/// - Standard try/catch pattern for Supabase calls
/// - Forensic payload hashing for INSERT operations with DB-generated IDs
///
/// Usage:
/// ```dart
/// class MyRepository extends BasePostgresRepository implements IMyRepository {
///   Future<MyEntity?> findById(String id) async {
///     return withErrorHandler(
///       'my_entity',
///       id,
///       () async {
///         final data = await client.from('my_table').select().eq('id', id).maybeSingle();
///         if (data == null) return null;
///         return _mapToEntity(data);
///       },
///     );
///   }
///
///   Future<void> insert(MyEntity entity, Map<String, dynamic> payload) async {
///     return withErrorHandler(
///       'my_entity',
///       null,  // ID not yet known — generated by DB
///       () async { await client.from('my_table').insert(payload); },
///       insertPayload: payload,  // ← SHA-256 hash for forensic traceability
///     );
///   }
/// }
/// ```
abstract class BasePostgresRepository with PostgresErrorInterceptor {
  final SupabaseClient client;

  BasePostgresRepository(this.client);

  /// Executes a Supabase operation with automatic PostgREST error handling.
  ///
  /// [resourceType] — domain name of the resource (e.g., 'contract').
  /// [resourceId] — entity ID if known (Dart-generated UUID). If null (DB-generated ID),
  ///   the [insertPayload] will be SHA-256 hashed to provide forensic traceability.
  /// [operation] — the Supabase call to execute.
  /// [insertPayload] — optional raw payload for INSERT operations. Used to generate
  ///   a forensic hash when [resourceId] is null.
  ///
  /// On [PostgrestException], the error is translated to a domain exception
  /// with full forensic metadata — never leaks raw DB error codes to the caller (INV-26).
  Future<T> withErrorHandler<T>(
    String resourceType,
    String? resourceId,
    Future<T> Function() operation, {
    Map<String, dynamic>? insertPayload,
  }) async {
    try {
      return await operation();
    } on PostgrestException catch (e) {
      // INV-26 + SOC Correlation: If resourceId is null (DB-generated ID),
      // generate a SHA-256 hash of the insert payload so the SOC can correlate
      // the failure to a specific payload, even without a UUID.
      final forensicResourceId =
          resourceId ?? _hashPayloadIfPresent(insertPayload);

      throw mapPostgrestToDomainException(
        e,
        resourceType: resourceType,
        resourceId: forensicResourceId,
      );
    }
  }

  // ── Optimistic Locking Support ────────────────────────────────────────

  /// Executes an UPDATE with optimistic locking via version column.
  ///
  /// **How it works:**
  /// 1. Filters the update by `.eq('version', currentVersion)` — if another
  ///    user has already bumped the version, this filter matches zero rows.
  /// 2. Appends `.select('id, version').maybeSingle()` to detect whether the
  ///    update actually found and modified a row.
  /// 3. If the result is null:
  ///    a. First, check if the row still exists (without version filter).
  ///    b. If it exists → [ConflictException.staleVersion] (another user won)
  ///    c. If it doesn't → [ConflictException.deleted] (resource was deleted)
  ///
  /// **Why this pattern:** Supabase/PostgREST does not return the number of
  /// affected rows. The only way to detect "zero rows matched" is to request
  /// the updated row back and check if it comes back.
  ///
  /// **Return value:** Returns the DB-assigned `version` after the update.
  /// The caller MUST use this value to update its local entity reference,
  /// otherwise subsequent updates on the same entity will fail with a
  /// [ConflictException] (stale version).
  ///
  /// [table] — Postgres table name (e.g., 'contracts').
  /// [data] — the update payload (WITHOUT version field — trigger handles it).
  /// [id] — primary key of the row to update.
  /// [currentVersion] — the version the client read before editing.
  /// [resourceType] — domain name for error messages (e.g., 'contract').
  ///
  /// Returns the updated `version` assigned by the database trigger.
  Future<int> updateWithVersion({
    required String table,
    required Map<String, dynamic> data,
    required String id,
    required int currentVersion,
    required String resourceType,
  }) async {
    // Step 1: Attempt update filtered by expected version.
    // The DB trigger bumps version to currentVersion + 1 on success.
    // maybeSingle() may throw PGRST116 when 0 rows — treat as null.
    Map<String, dynamic>? updated;
    try {
      updated = await client
          .from(table)
          .update(data)
          .eq('id', id)
          .eq('version', currentVersion)
          .select('id, version')
          .maybeSingle();
    } on PostgrestException catch (e) {
      if (e.code != 'PGRST116' && e.code != '406') rethrow;
      updated = null;
    }

    if (updated != null) {
      // Happy path: update succeeded, trigger incremented version.
      return updated['version'] as int;
    }

    // Step 2: Conflict or deletion — discriminate forensically.
    // maybeSingle() may throw PGRST116 when 0 rows — treat as null.
    Map<String, dynamic>? exists;
    try {
      exists = await client
          .from(table)
          .select('id, version')
          .eq('id', id)
          .maybeSingle();
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116' || e.code == '406') {
        exists = null;
      } else {
        rethrow;
      }
    }

    if (exists == null) {
      // Resource was deleted by another user while we were editing.
      throw ConflictException.deleted(
        resourceType: resourceType,
        resourceId: id,
        clientVersion: currentVersion,
      );
    }

    // Resource exists but at a different version → stale write.
    final serverVersion = exists['version'] as int?;
    throw ConflictException.staleVersion(
      resourceType: resourceType,
      resourceId: id,
      clientVersion: currentVersion,
      currentVersion: serverVersion ?? -1,
    );
  }

  // ── Batch Update with Optimistic Locking (Atomic via RPC) ──────────────

  /// Executes a batch UPDATE with **atomic** optimistic locking via Postgres RPC.
  ///
  /// **Guarantee:** If ANY entity has a stale version, the ENTIRE batch is
  /// rolled back by Postgres — zero partial commits possible.
  ///
  /// **How it works:**
  /// 1. Encodes all update specs as JSONB
  /// 2. Calls the table-specific RPC function (`batch_update_{table}`)
  /// 3. The RPC verifies ALL versions BEFORE any write, then updates in one txn
  /// 4. On conflict: P0001 exception → mapped to [ConflictException] with stale IDs
  ///
  /// **TOCTOU protection:** The RPC re-checks versions with WHERE clauses and
  /// uses `GET DIAGNOSTICS ROW_COUNT` to detect concurrent modifications.
  ///
  /// [rpcFunction] — the Postgres RPC name (e.g., `batch_update_vehicles`).
  /// [updates] — list of update specs (id, version, data payload).
  ///
  /// Returns the number of successfully updated entities.
  Future<int> batchUpdateWithVersion({
    required String rpcFunction,
    required List<BatchUpdateSpec> updates,
  }) async {
    if (updates.isEmpty) return 0;

    // Encode as JSONB array: [{id, version, data}, ...]
    final jsonUpdates = updates.map((spec) {
      final map = <String, dynamic>{'id': spec.id, 'version': spec.version};
      map.addAll(spec.data);
      return map;
    }).toList();

    try {
      final result = await client.rpc(
        rpcFunction,
        params: {'p_updates': jsonUpdates},
      );
      final resultMap = result as Map<String, dynamic>;
      return resultMap['updated_count'] as int;
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116' ||
          e.message.contains('P0001') ||
          e.message.contains('Batch conflict') ||
          e.message.contains('stale')) {
        // Extract stale IDs from error message
        final staleIds = _extractStaleIds(e.message);
        throw ConflictException.staleVersion(
          resourceType: 'batch',
          resourceId: staleIds.join(', '),
          clientVersion: -1,
          currentVersion: -1,
        );
      }
      rethrow;
    }
  }

  /// Extracts entity IDs from a batch conflict error message.
  static List<String> _extractStaleIds(String message) {
    // Pattern: "Batch conflict: vehicle abc-123 is stale" or
    //          "Batch conflict: vehicle abc-123 was modified concurrently"
    final ids = <String>[];
    final matches = RegExp(
      r'(?:vehicle|contract)\s+([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})',
    ).allMatches(message.toLowerCase());
    for (final match in matches) {
      if (match.groupCount >= 1) {
        final id = match.group(1);
        if (id != null) ids.add(id);
      }
    }
    return ids.isEmpty ? ['unknown'] : ids;
  }

  /// Generates a SHA-256 hex digest of a JSON payload for forensic traceability.
  ///
  /// Returns null if payload is null or empty.
  /// The hash allows the SOC to correlate a failure to a specific payload even
  /// when the database-generated ID is not yet known.
  ///
  /// **INV-15 (Deterministic):** Keys are sorted alphabetically before encoding
  /// to ensure canonical JSON — identical to the Deno `sortKeys()` function used
  /// by the HMAC verification worker. Without this, Dart's `jsonEncode` preserves
  /// Map insertion order, which would produce different hashes than the Deno side.
  ///
  /// **INV-9 (Evidence Sealing):** Type normalization is applied before hashing:
  /// `DateTime` objects are converted to ISO-8601 strings so that Dart and Deno
  /// produce byte-identical JSON for the same logical payload.
  static String? _hashPayloadIfPresent(Map<String, dynamic>? payload) {
    if (payload == null || payload.isEmpty) return null;
    final canonicalJson = jsonEncode(_sortKeys(payload));
    return sha256.convert(utf8.encode(canonicalJson)).toString();
  }

  /// Recursively sorts Map keys alphabetically and normalizes types for
  /// canonical JSON serialization.
  ///
  /// Dart's `jsonEncode` preserves Map insertion order. To ensure identical hashes
  /// between Dart (insert) and Deno (verification), keys MUST be sorted
  /// alphabetically — matching the Deno `sortKeys()` function in `canonical_json.ts`.
  ///
  /// **Type normalization (INV-9 parity):**
  /// - `DateTime` → ISO-8601 string with 'Z' suffix (e.g. `2026-04-11T00:00:00.000Z`)
  /// - `Map<String, dynamic>` → keys sorted, values recursively normalized
  /// - `List<dynamic>` → each element recursively normalized
  /// - Primitives (null, String, int, double, bool) → returned as-is
  ///
  /// This ensures that a `DateTime` embedded in a nested list or map is
  /// serialized identically on both Dart and Deno sides before hashing.
  static dynamic _sortKeys(dynamic obj) {
    if (obj == null) return null;

    // Type normalization: DateTime → ISO-8601 string (Z-suffix for UTC parity)
    if (obj is DateTime) {
      final iso = obj.toUtc().toIso8601String();
      // Ensure 'Z' suffix for deterministic parity with Deno
      return iso.endsWith('Z') ? iso : '${iso}Z';
    }

    // Recursive map: sort keys + normalize values
    if (obj is Map<String, dynamic>) {
      final sorted = <String, dynamic>{};
      final keys = obj.keys.toList()..sort();
      for (final key in keys) {
        sorted[key] = _sortKeys(obj[key]);
      }
      return sorted;
    }

    // Recursive list: normalize each element
    if (obj is List) {
      return obj.map(_sortKeys).toList();
    }

    // Case base: primitives (String, int, double, bool, num) pass through
    return obj;
  }

  // ── Test Hooks (public access to private static methods) ──────────────────

  /// Public wrapper for [_hashPayloadIfPresent] — used by tests to verify
  /// deterministic hashing without exposing the private method.
  @visibleForTesting
  static String? hashPayload(Map<String, dynamic>? payload) {
    return _hashPayloadIfPresent(payload);
  }

  /// Public wrapper for [_sortKeys] — used by tests to verify canonical
  /// JSON serialization and type normalization.
  @visibleForTesting
  static dynamic sortKeys(dynamic obj) {
    return _sortKeys(obj);
  }

  /// Returns the canonical JSON string for a payload (sorted keys + normalized
  /// types). Useful for debugging hash mismatches and verifying parity with
  /// the Deno `canonical_json.ts` implementation.
  @visibleForTesting
  static String canonicalJson(Map<String, dynamic> payload) {
    return jsonEncode(_sortKeys(payload));
  }
}

/// Immutable specification for a single batch update entry.
///
/// Used with [BasePostgresRepository.batchUpdateWithVersion] to define
/// which entity to update, what version it must have, and what data to write.
class BatchUpdateSpec {
  /// Primary key of the entity to update.
  final String id;

  /// Expected version number (optimistic lock).
  final int version;

  /// Data fields to update (key-value pairs, same as .update() payload).
  final Map<String, dynamic> data;

  const BatchUpdateSpec({
    required this.id,
    required this.version,
    required this.data,
  });
}
