import 'package:veraprob/domain/enums/user_role.dart';

/// Port for invitation lifecycle mutations.
/// Concrete implementation: [PostgresInvitationCommandService].
abstract class InvitationCommandService {
  /// Atomically revokes any pending invite for [email] in the caller's org
  /// and inserts a new invitation. IDs and token are generated by the caller
  /// (Invariant 7: Deterministic Replay).
  Future<void> inviteUser({
    required String email,
    required UserRole role,
    String? tenantRoleId,
    required String token,
    required String invitationId,
    required DateTime expiresAtUtc,
  });

  /// Marks the invitation identified by [token] as accepted and inserts
  /// the [userId] into [user_roles]. Enforced atomically by server-side RPC.
  Future<void> acceptInvitation({
    required String token,
    required String userId,
  });

  /// Revokes a pending invitation by [invitationId].
  /// Server-side validates that the invitation belongs to the caller's org.
  Future<void> revokeInvitation({required String invitationId});
}
