import '../../domain/sla_audit/contractual_execution_state.dart';
import '../../domain/sla_audit/evaluation_trace.dart';
import '../../domain/sla_audit/execution_status.dart';
import '../../domain/sla_audit/operational_alert.dart';

/// Derives operational alerts from evaluation results.
///
/// This is the single point of alert derivation — alerts originate
/// exclusively from the ContractualEvaluationEngine pipeline.
class AlertDerivationService {
  AlertDerivationService._();

  /// Derives an [OperationalAlert] from an execution state transition.
  ///
  /// Returns `null` if no alert is warranted (e.g., successful execution
  /// without penalties, or still pending).
  static OperationalAlert? deriveFrom({
    required ContractualExecutionState state,
    required List<EvaluationDecision> decisions,
    required DateTime evaluatedAtUtc,
    String? triggeringEventId,
    String? traceId,
  }) {
    switch (state.status) {
      case ExecutionStatus.noShow:
        return OperationalAlert(
          id: '', // Generated by repository
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'NO_SHOW',
          severity: 'CRITICAL',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: {
            'window_start': state.windowStartUtc.toIso8601String(),
            'window_end': state.windowEndUtc.toIso8601String(),
            'plan_version': state.planVersion,
          },
        );

      case ExecutionStatus.evidenceGap:
        return OperationalAlert(
          id: '',
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'EVIDENCE_GAP',
          severity: 'WARNING',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: {
            'window_start': state.windowStartUtc.toIso8601String(),
            'window_end': state.windowEndUtc.toIso8601String(),
            'plan_version': state.planVersion,
          },
        );

      case ExecutionStatus.executed:
        // Check if any penalty was applied
        final hasPenalty = decisions.any(
          (d) => d.financialImpactCents != null && d.financialImpactCents! > 0,
        );
        if (!hasPenalty) return null;

        final totalPenaltyCents = decisions
            .where(
              (d) =>
                  d.financialImpactCents != null && d.financialImpactCents! > 0,
            )
            .fold<int>(0, (sum, d) => sum + d.financialImpactCents!);

        return OperationalAlert(
          id: '',
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'PENALTY_APPLIED',
          severity: 'HIGH',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: {
            'total_penalty_cents': totalPenaltyCents,
            'penalty_decisions': decisions
                .where(
                  (d) =>
                      d.financialImpactCents != null &&
                      d.financialImpactCents! > 0,
                )
                .map((d) => d.ruleType)
                .toList(),
            'plan_version': state.planVersion,
          },
        );

      case ExecutionStatus.pending:
        return null; // No alert for pending evaluations
    }
  }
}
