import 'package:veraprob/domain/shared/integrity_exception.dart';
import 'package:veraprob/domain/sla_audit/contractual_execution_state.dart';
import 'package:veraprob/domain/sla_audit/evaluation_trace.dart';
import 'package:veraprob/domain/sla_audit/execution_status.dart';
import 'package:veraprob/domain/sla_audit/operational_alert.dart';

/// Derives operational alerts from evaluation results.
///
/// This is the single point of alert derivation — alerts originate
/// exclusively from the ContractualEvaluationEngine pipeline.
class AlertDerivationService {
  AlertDerivationService._();

  // Alert types that require driver attribution (INV-18: Zero-Trust telemetry).
  // TELEGRAM_ORPHAN is exempt: orphan = message not yet linked to any driver.
  static const _driverBoundTypes = {
    'NO_SHOW',
    'EVIDENCE_GAP',
    'PENALTY_APPLIED',
    'DEVIATION',
    'SLA_BREACH',
    'POTENTIAL_TIME_FRAUD',
  };

  /// Derives an [OperationalAlert] from an execution state transition.
  ///
  /// Returns `null` if no alert is warranted (e.g., successful execution
  /// without penalties, or still pending).
  ///
  /// [driverId] and [driverName] are optional enrichment fields included
  /// in the alert context for downstream grouping (Command Center).
  static OperationalAlert? deriveFrom({
    required ContractualExecutionState state,
    required List<EvaluationDecision> decisions,
    required DateTime evaluatedAtUtc,
    String? triggeringEventId,
    String? traceId,
    String? driverId,
    String? driverName,
  }) {
    switch (state.status) {
      case ExecutionStatus.failed:
        return OperationalAlert(
          id: '', // Generated by repository
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'NO_SHOW',
          severity: 'CRITICAL',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: _buildContext(
            alertType: 'NO_SHOW',
            base: {
              'window_start': state.windowStartUtc.toIso8601String(),
              'window_end': state.windowEndUtc.toIso8601String(),
              'plan_version': state.planVersion,
            },
            driverId: driverId,
            driverName: driverName,
          ),
        );

      case ExecutionStatus.completedWithGaps:
        return OperationalAlert(
          id: '',
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'EVIDENCE_GAP',
          severity: 'WARNING',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: _buildContext(
            alertType: 'EVIDENCE_GAP',
            base: {
              'window_start': state.windowStartUtc.toIso8601String(),
              'window_end': state.windowEndUtc.toIso8601String(),
              'plan_version': state.planVersion,
            },
            driverId: driverId,
            driverName: driverName,
          ),
        );

      case ExecutionStatus.completed:
        // Check if any penalty was applied
        final hasPenalty = decisions.any(
          (d) => d.financialImpactCents != null && d.financialImpactCents! > 0,
        );
        if (!hasPenalty) return null;

        final totalPenaltyCents = decisions
            .where(
              (d) =>
                  d.financialImpactCents != null && d.financialImpactCents! > 0,
            )
            .fold<int>(0, (sum, d) => sum + d.financialImpactCents!);

        return OperationalAlert(
          id: '',
          organizationId: state.organizationId,
          entityId: state.setId,
          contractId: state.contractId,
          alertType: 'PENALTY_APPLIED',
          severity: 'HIGH',
          triggeredAtUtc: evaluatedAtUtc,
          triggeringEventId: triggeringEventId,
          traceId: traceId,
          context: _buildContext(
            alertType: 'PENALTY_APPLIED',
            base: {
              'total_penalty_cents': totalPenaltyCents,
              'penalty_decisions': decisions
                  .where(
                    (d) =>
                        d.financialImpactCents != null &&
                        d.financialImpactCents! > 0,
                  )
                  .map((d) => d.ruleType)
                  .toList(),
              'plan_version': state.planVersion,
            },
            driverId: driverId,
            driverName: driverName,
          ),
        );

      case ExecutionStatus.planned:
      case ExecutionStatus.inTransit:
        return null; // No alert for pre-outcome states

      case ExecutionStatus.inhibited:
        return null; // Penalty suppressed by approved justification — no alert
    }
  }

  /// Merges driver enrichment into the alert context.
  ///
  /// Throws [IntegrityException] when [alertType] is driver-bound (INV-18)
  /// and [driverId] is not supplied.
  static Map<String, dynamic> _buildContext({
    required Map<String, dynamic> base,
    required String alertType,
    String? driverId,
    String? driverName,
  }) {
    if (_driverBoundTypes.contains(alertType) && driverId == null) {
      throw IntegrityException(
        'Alert type $alertType requires driver attribution (INV-18)',
        field: 'driver_id',
      );
    }
    return {...base, 'driver_id': ?driverId, 'driver_name': ?driverName};
  }
}
