import 'package:veraprob/domain/enums/user_role.dart';

/// Immutable command DTO for closing an existing [Contract].
///
/// Contains ZERO logic. Carries only the data required by
/// [CloseContractHandler] to transition a contract to [closed].
///
/// [organizationId] and [callerRole] must be injected from the
/// authenticated JWT — never from form input.
///
/// **INV-33 (Idempotency):** [idempotencyKey] is a client-generated UUID
/// that ensures duplicate requests (duplicate clicks, retries) never produce
/// duplicate side-effects. The key is checked BEFORE any business logic
/// executes. If the same key is used twice, the second request returns
/// the cached response from the first.
class CloseContractCommand {
  final String organizationId;
  final String contractId;
  final String closedByUserId;
  final String reason;

  /// The role of the user issuing this command.
  /// Must be sourced from [currentUserRoleProvider] (JWT claim) — never
  /// from user input. Used by [CloseContractHandler] to enforce RBAC
  /// before any I/O is performed.
  final UserRole callerRole;

  /// Session ID for tenant validation.
  final String sessionId;

  /// Idempotency key (UUID v4) generated by the client.
  /// Ensures duplicate requests return the cached response (INV-33).
  final String idempotencyKey;

  const CloseContractCommand({
    required this.organizationId,
    required this.contractId,
    required this.closedByUserId,
    required this.reason,
    required this.callerRole,
    required this.sessionId,
    required this.idempotencyKey,
  });
}
