-- =============================================================================
-- Migration: Sprint B — Rule Lifecycle Ledger Types
-- =============================================================================

-- ADD _v4 NOT VALID -> VALIDATE -> DROP antigo -> RENAME de volta ao nome canônico
-- Also add Sprint B types: RULE_SCHEDULED, RULE_ACTIVATED, RULE_RETIRED, CONTRACT_FINANCIAL_TERMS_AMENDED

ALTER TABLE public.sla_audit_ledger_v2
  ADD CONSTRAINT chk_ledger_type_v4 CHECK (type IN (
    'EXECUTION_BOUND','NO_SHOW_DECLARED','EVIDENCE_GAP_DECLARED','PLAN_DECLARED',
    'OCCURRENCE_REGISTERED','TRIP_INTERRUPTED','TRIP_CANCELLED','CONTRACT_CREATED',
    'CONTRACT_ACTIVATED','CONTRACT_CLOSED','CONTRACT_SUBMITTED_FOR_APPROVAL',
    'CONTRACT_ACCEPTED_BY_CONTRACTOR','SANCTION_RECOMMENDED','VERDICT_SEALED',
    'VERDICT_REFUSED','SANCTION_DISPUTED','DISPUTE_ACCEPTED','DISPUTE_OVERTURNED',
    'DISPUTE_RETRACTED','JUSTIFICATION_SUBMITTED','JUSTIFICATION_APPROVED',
    'JUSTIFICATION_REJECTED','SLA_JUSTIFICATION_SUBMITTED','SLA_JUSTIFICATION_EXPIRED',
    'TRANSIT_STARTED','COMPLETED_WITH_GAPS','EXECUTION_INHIBITED','UNKNOWN_EVENT',
    'MAX_TOLERANCE_DELAY','MAX_EVIDENCE_GAP','MIN_GEOFENCE_COVERAGE','NO_SHOW_PENALTY',
    'PEER_REVIEW_REQUESTED','PEER_REVIEW_DECLINED','PEER_REVIEW_EXPIRED',
    'DUAL_CONTROL_THRESHOLD_CHANGED',
    'DISPUTE_EVIDENCE_ATTACHED','DISPUTE_SLA_BREACHED','EVIDENCE_HASH_MISMATCH',
    'DISPUTE_PORTAL_TOKEN_GENERATED','DISPUTE_PORTAL_TOKEN_ACCESSED','DISPUTE_PORTAL_TOKEN_REVOKED',
    -- Sprint B
    'RULE_SCHEDULED', 'RULE_ACTIVATED', 'RULE_RETIRED', 'CONTRACT_FINANCIAL_TERMS_AMENDED'
  )) NOT VALID;

ALTER TABLE public.sla_audit_ledger_v2 VALIDATE CONSTRAINT chk_ledger_type_v4;

ALTER TABLE public.sla_audit_ledger_v2 DROP CONSTRAINT IF EXISTS chk_ledger_type; -- INV-DB: zero-downtime-verified

ALTER TABLE public.sla_audit_ledger_v2 RENAME CONSTRAINT chk_ledger_type_v4 TO chk_ledger_type;
