-- ============================================================
-- PactaFlow — Phase 5 B2B Refactoring: Database Foundation
-- ============================================================
-- REASON:
--   Phase 5 baseline (5.3) stored raw GPS coordinates and absolute
--   UTC timestamps per SET — forcing operators to input geospatial
--   data manually. The B2B Refactoring introduces:
--
--     1. OperationalZone — named geofenced areas (e.g. "Garagem Central")
--     2. ShiftPattern     — recurrence rules stored in plan_declarations JSONB
--     3. SLAPenalties     — margin offenders snapshotted per projected SET
--
--   Projected SETs are generated by ShiftProjectionService (Dart),
--   not by the operator. Zone coordinates are snapshotted at projection
--   time into contractual_service_executions to preserve replay determinism.
--
-- INVARIANTS ENFORCED:
--   - RLS: (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid on every table
--   - Financial precision: penalty values stored as BIGINT cents
--   - Idempotency: unique partial index prevents duplicate projected SETs
--   - Zone immutability: ON DELETE RESTRICT prevents zone deletion if
--     referenced by projected SETs (audit trail preserved)
--
-- APPLIES TO: dev environment after full schema reset
-- ============================================================

-- ── 1. operational_zones ────────────────────────────────────
--
-- Named geofenced areas owned by an organization.
-- Operators reference zones by name (not lat/lng) when declaring plans.
-- Coordinates are SNAPSHOTTED into contractual_service_executions at
-- projection time — updating a zone does NOT affect historical SETs.

CREATE TABLE public.operational_zones (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id),
  name            TEXT        NOT NULL,
  latitude        DOUBLE PRECISION NOT NULL
                              CHECK (latitude  BETWEEN -90  AND 90),
  longitude       DOUBLE PRECISION NOT NULL
                              CHECK (longitude BETWEEN -180 AND 180),
  radius_meters   INTEGER     NOT NULL
                              CHECK (radius_meters > 0 AND radius_meters <= 50000),
  created_at_utc  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Ensure zone names are unique per organization
  CONSTRAINT uq_zone_name_per_org UNIQUE (organization_id, name)
);

-- Performance: operator zone picker queries by org
CREATE INDEX idx_operational_zones_org
  ON public.operational_zones (organization_id);

-- ── RLS: operational_zones ───────────────────────────────────
ALTER TABLE public.operational_zones ENABLE ROW LEVEL SECURITY;

-- Operators only see and write zones belonging to their own organization.
-- organization_id is derived exclusively from the JWT (app_metadata.org_id).
CREATE POLICY "Zone tenant isolation"
  ON public.operational_zones FOR ALL TO authenticated
  USING     (organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::UUID)
  WITH CHECK (organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::UUID);


-- ── 2. plan_declarations: ShiftPattern payload ──────────────
--
-- ShiftPatterns are components of the PlanDeclaration aggregate.
-- Stored as JSONB (not a separate table) to preserve aggregate boundary.
-- Structure: [{ "index": 0, "daysOfWeek": [1,2,3,4,5],
--               "arrivalTimeLocal": "07:00", "departureTimeLocal": "06:30",
--               "timezone": "America/Sao_Paulo",
--               "originZoneId": "<uuid>", "destinationZoneId": "<uuid>",
--               "penalties": { "noShowMultiplier": 1.5,
--                              "delayToleranceMinutes": 15,
--                              "delayPenaltyPerMinuteCents": 1000,
--                              "downgradePenaltyFlatCents": 50000 } }]
ALTER TABLE public.plan_declarations
  ADD COLUMN IF NOT EXISTS shift_patterns_payload JSONB;


-- ── 3. contractual_service_executions: B2B columns ──────────
--
-- New columns support projected SETs from ShiftPatterns.
-- All columns are nullable: existing manual SETs have NULL values.
-- Projected SETs populate all new columns.

-- Zone audit trail (snapshot at projection time — NOT re-resolved later)
ALTER TABLE public.contractual_service_executions
  ADD COLUMN IF NOT EXISTS origin_zone_id      UUID
    REFERENCES public.operational_zones(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS destination_zone_id UUID
    REFERENCES public.operational_zones(id) ON DELETE RESTRICT;

-- Projection metadata (links SET back to its ShiftPattern + date)
ALTER TABLE public.contractual_service_executions
  ADD COLUMN IF NOT EXISTS operational_date     DATE,
  ADD COLUMN IF NOT EXISTS shift_pattern_index  INTEGER;

-- SLA Penalties snapshot (captured at projection time from SLAPenalties VO)
-- Financial fields stored as BIGINT cents — invariant enforced.
ALTER TABLE public.contractual_service_executions
  ADD COLUMN IF NOT EXISTS delay_tolerance_minutes          INTEGER,
  ADD COLUMN IF NOT EXISTS delay_penalty_per_minute_cents   BIGINT
    CHECK (delay_penalty_per_minute_cents >= 0),
  ADD COLUMN IF NOT EXISTS downgrade_penalty_flat_cents     BIGINT
    CHECK (downgrade_penalty_flat_cents >= 0);

-- ── 4. Idempotency constraint for projected SETs ────────────
--
-- Prevents duplicate SET generation when ShiftProjectionService
-- runs more than once for the same plan + shift + date.
-- Partial index: only applies to projected SETs (shift_pattern_index IS NOT NULL).
-- Manual SETs (existing baseline) are unaffected.
CREATE UNIQUE INDEX idx_set_projection_idempotency
  ON public.contractual_service_executions (
    plan_declaration_id,
    shift_pattern_index,
    operational_date
  )
  WHERE shift_pattern_index IS NOT NULL;

-- Performance: query projected SETs by operational date range
CREATE INDEX idx_set_operational_date
  ON public.contractual_service_executions (operational_date)
  WHERE operational_date IS NOT NULL;
