-- Migration: 20260305194500_explainability_traces.sql
-- Description: Creates the append-only investigative read model for Evaluation Traces, ensuring segregation from operational projections.

-- 1. Create the Evaluation Traces Table
CREATE TABLE IF NOT EXISTS public.contractual_evaluation_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    entity_id TEXT NOT NULL, -- e.g., trip_id or set_id string for generic lookup
    -- NOTE: FK to sla_audit_ledger_v2 omitted intentionally.
    -- sla_audit_ledger_v2 is HASH-partitioned with composite PK (organization_id, id).
    -- PostgreSQL does not support FKs referencing a partial composite PK on partitioned tables.
    -- The column was also incorrectly referencing 'event_id' (non-existent); the correct column is 'id'.
    -- Referential integrity is enforced at the application layer.
    triggering_event_id UUID NOT NULL,
    evaluated_at_utc TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    engine_version TEXT NOT NULL,
    decisions_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 2. Performance Indices
-- Accelerates retrieving traces for a specific entity (e.g. trip) within a tenant.
CREATE INDEX IF NOT EXISTS idx_evaluation_traces_entity_id 
ON public.contractual_evaluation_traces (organization_id, entity_id);

-- Accelerates retrieving the exact trace generated by a specific event.
CREATE INDEX IF NOT EXISTS idx_evaluation_traces_triggering_event
ON public.contractual_evaluation_traces (organization_id, triggering_event_id);

-- 3. Row-Level Security (Strict Tenant Isolation)
ALTER TABLE public.contractual_evaluation_traces ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant Isolation: Maintainers can read their traces"
ON public.contractual_evaluation_traces
FOR SELECT
USING (
  organization_id = (current_setting('request.jwt.claims', true)::json->'app_metadata'->>'organization_id')::uuid
);

CREATE POLICY "Tenant Isolation: Maintainers can insert their traces"
ON public.contractual_evaluation_traces
FOR INSERT
WITH CHECK (
  organization_id = (current_setting('request.jwt.claims', true)::json->'app_metadata'->>'organization_id')::uuid
);

-- 4. Invariant: Append-Only Immutable Investigation Data
-- We MUST NOT allow UPDATE or DELETE operations to evaluation traces to protect the forensic chain.
REVOKE UPDATE, DELETE ON public.contractual_evaluation_traces FROM authenticated, anon;
