-- Suppress DROP TRIGGER/POLICY IF EXISTS NOTICEs (objects don't exist on fresh reset).
SET client_min_messages TO 'WARNING';

-- =============================================================================
-- Migration: 20260413000002 — Idempotency Keys Infrastructure (INV-33)
--
-- PURPOSE:
--   Implements command-level idempotency to guarantee that duplicate requests
--   (double-clicks, network retries, infrastructure failures) never produce
--   duplicate side-effects.
--
-- DESIGN:
--   - Idempotency keys are stored in Postgres (NOT in-memory) to survive
--     process restarts and horizontal scaling.
--   - Keys are scoped to (id, user_id) — each user has independent idempotency.
--   - The key is registered BEFORE business logic executes, then updated to
--     'completed' WITH the response body AFTER persistence succeeds.
--   - All three steps (check key → execute → update key) occur within a SINGLE
--     database transaction. If business logic fails, the key registration is
--     rolled back atomically — no orphaned 'processing' keys.
--
-- INVARIANTS:
--   INV-1:  organization_id filters all queries (tenant isolation).
--   INV-6:  All timestamps are UTC.
--   INV-9:  response_body stored as canonical JSON for replay parity.
--   INV-26: Error parity — 404 for 'not found' AND 'other org' (handled in app layer).
--   INV-30: SupabaseClient injected via constructor (DI Total).
--   INV-32: response_body includes the updated version (V+2) for optimistic locking.
--   INV-33: Idempotency keys — new invariant introduced by this migration.
--
-- INV-33 RULES:
--   (a) Every mutating command MUST carry an idempotencyKey generated by the client.
--   (b) The key is CHECKed before any business logic executes.
--   (c) If key status = 'completed' → return cached response_body (short-circuit).
--   (d) If key status = 'processing' → reject with IdempotencyProcessingException
--       (another thread is already handling this request).
--   (e) If key is null → INSERT as 'processing', execute business logic, then
--       UPDATE to 'completed' with response_body — all within one transaction.
--   (f) If the transaction rolls back, the key registration is also rolled back.
-- =============================================================================

-- ── 1. idempotency_keys table ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.idempotency_keys (
  id              TEXT        NOT NULL,
  user_id         UUID        NOT NULL
    REFERENCES auth.users(id) ON DELETE CASCADE,
  command_path    TEXT        NOT NULL,
  organization_id UUID        NOT NULL,
  status          TEXT        NOT NULL
    CHECK (status IN ('processing', 'completed', 'error')),
  response_code   INT,
  response_body   JSONB,
  created_at_utc  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at_utc TIMESTAMPTZ,

  -- Per-key stale threshold (minutes). Heavy commands (e.g., monthly audit)
  -- can set 30+ to prevent premature reclamation. Default: 5.
  stale_threshold_minutes INT NOT NULL DEFAULT 5,

  -- Composite primary key: (id, user_id) ensures per-user idempotency.
  PRIMARY KEY (id, user_id)
);

-- Index for fast lookup by user + status (cleanup query).
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_user_status
  ON public.idempotency_keys (user_id, status);

-- Index for cleanup: find old completed/error keys by age.
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_created_at
  ON public.idempotency_keys (created_at_utc);

-- Index for organization-scoped queries (audit/debug).
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_org
  ON public.idempotency_keys (organization_id);

-- ── 2. RLS policies ─────────────────────────────────────────────────────────

ALTER TABLE public.idempotency_keys ENABLE ROW LEVEL SECURITY;

-- Users can only see their own idempotency keys.
DROP POLICY IF EXISTS idempotency_keys_select_own
  ON public.idempotency_keys;
CREATE POLICY idempotency_keys_select_own
  ON public.idempotency_keys
  FOR SELECT
  USING (
    user_id = auth.uid()
  );

-- Users can only insert their own keys (status = 'processing' on creation).
DROP POLICY IF EXISTS idempotency_keys_insert_own
  ON public.idempotency_keys;
CREATE POLICY idempotency_keys_insert_own
  ON public.idempotency_keys
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND status = 'processing'
  );

-- Users can only update their own keys (processing → completed/error).
DROP POLICY IF EXISTS idempotency_keys_update_own
  ON public.idempotency_keys;
CREATE POLICY idempotency_keys_update_own
  ON public.idempotency_keys
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (
    user_id = auth.uid()
    AND status IN ('completed', 'error')
  );

-- Service role bypass (for server-side command handlers).
DROP POLICY IF EXISTS idempotency_keys_service_all
  ON public.idempotency_keys;
CREATE POLICY idempotency_keys_service_all
  ON public.idempotency_keys
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ── 3. Immutable fields after creation ───────────────────────────────────────
--    Only status, response_code, response_body, and completed_at_utc can change.
--    id, user_id, command_path, organization_id, created_at_utc are frozen.

CREATE OR REPLACE FUNCTION public.prevent_idempotency_key_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id                IS DISTINCT FROM OLD.id                OR
     NEW.user_id           IS DISTINCT FROM OLD.user_id           OR
     NEW.command_path      IS DISTINCT FROM OLD.command_path      OR
     NEW.organization_id   IS DISTINCT FROM OLD.organization_id   OR
     NEW.created_at_utc    IS DISTINCT FROM OLD.created_at_utc
  THEN
    RAISE EXCEPTION
      'idempotency_keys: immutable field mutation. id: %, user_id: %',
      OLD.id, OLD.user_id
    USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_idempotency_keys_no_mutation
  ON public.idempotency_keys;
CREATE TRIGGER trg_idempotency_keys_no_mutation
  BEFORE UPDATE ON public.idempotency_keys
  FOR EACH ROW EXECUTE FUNCTION public.prevent_idempotency_key_mutation();

-- ── 4. Cleanup function ─────────────────────────────────────────────────────
--    Removes completed/error keys older than N days to prevent table bloat.
--    This is a maintenance function — should be called by a cron job or
--    Supabase scheduled job (e.g., daily).

CREATE OR REPLACE FUNCTION public.cleanup_expired_idempotency(
  days_threshold INT DEFAULT 30
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cutoff   TIMESTAMPTZ;
  v_deleted  INT;
BEGIN
  v_cutoff := NOW() - (days_threshold || ' days')::INTERVAL;

  -- Delete old completed/error keys.
  -- 'processing' keys are NEVER deleted — they indicate an in-flight operation
  -- or a rolled-back transaction (which should be rare and investigated).
  DELETE
    FROM public.idempotency_keys
   WHERE status IN ('completed', 'error')
     AND created_at_utc < v_cutoff;

  GET DIAGNOSTICS v_deleted = ROW_COUNT;

  RETURN v_deleted;
END;
$$;

-- ── 5. Prevent deletion of 'processing' keys (safety net) ───────────────────

CREATE OR REPLACE FUNCTION public.prevent_idempotency_processing_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'processing' THEN
    RAISE EXCEPTION
      'idempotency_keys: cannot DELETE processing keys. id: %, user_id: %. '
      'This may indicate a rollback or orphaned transaction.',
      OLD.id, OLD.user_id
    USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_idempotency_no_delete_processing
  ON public.idempotency_keys;
CREATE TRIGGER trg_idempotency_no_delete_processing
  BEFORE DELETE ON public.idempotency_keys
  FOR EACH ROW EXECUTE FUNCTION public.prevent_idempotency_processing_delete();

-- ── 6. Comments for documentation ───────────────────────────────────────────

COMMENT ON TABLE public.idempotency_keys IS
  'Tracks idempotency keys for command-level deduplication (INV-33). '
  'Each key is scoped to a user and command. Status transitions: '
  'processing → completed (success) or error (failure). '
  'Completed keys store response_body for replay on duplicate requests.';

COMMENT ON COLUMN public.idempotency_keys.response_body IS
  'Canonical JSON snapshot of the command response. Includes updated '
  'entity version (V+2 for optimistic locking) for replay parity.';

COMMENT ON FUNCTION public.cleanup_expired_idempotency(INT) IS
  'Removes completed/error idempotency keys older than N days. '
  'Never deletes processing keys — they indicate in-flight or rolled-back transactions.';

-- ── 7. Atomic transactional RPC: register → execute → complete ──────────────
--
-- This function provides atomic idempotency for command execution.
-- It is called by the Dart application layer with a command identifier,
-- and wraps the entire check-register-execute-commit cycle in a single
-- database transaction.
--
-- FLOW:
--   1. Check if key exists with status = 'completed' → return cached response.
--   2. Check if key exists with status = 'processing' → raise exception (duplicate in-flight).
--   3. INSERT key as 'processing' (ON CONFLICT DO NOTHING for race condition safety).
--   4. If insert succeeded (another thread didn't beat us):
--      a. Caller executes business logic (outside this function).
--      b. Caller calls complete_idempotency_key() to mark as completed.
--   5. If insert failed (key already existed as 'processing'):
--      a. Raise exception — caller should abort.
--
-- NOTE: This function does NOT execute business logic itself. It only manages
-- the idempotency key state. The caller (Dart handler) is responsible for:
--   - Calling this function BEFORE business logic.
--   - Calling complete_idempotency_key() AFTER business logic succeeds.
--   - Calling fail_idempotency_key() if business logic fails.
--
-- This separation is intentional: business logic may involve multiple tables
-- and domain events that cannot be encapsulated in a single SQL function.

CREATE OR REPLACE FUNCTION public.try_acquire_idempotency_key(
  p_id                    TEXT,
  p_user_id               UUID,
  p_command_path          TEXT,
  p_organization_id       UUID,
  p_stale_threshold_min   INT DEFAULT 5
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_existing RECORD;
  v_inserted BOOLEAN;
  v_stale_threshold INTERVAL;
BEGIN
  -- Step 1: Check if key already exists.
  -- Read the per-key stale_threshold_minutes to avoid reclaiming heavy commands prematurely.
  SELECT status, response_code, response_body, created_at_utc, completed_at_utc,
         COALESCE(stale_threshold_minutes, 5) AS stale_threshold_minutes
    INTO v_existing
    FROM public.idempotency_keys
   WHERE id = p_id AND user_id = p_user_id
   LIMIT 1;

  -- Key found.
  IF FOUND THEN
    IF v_existing.status = 'completed' THEN
      -- Short-circuit: return cached response.
      RETURN jsonb_build_object(
        'hit', true,
        'status', 'completed',
        'response_code', v_existing.response_code,
        'response_body', v_existing.response_body,
        'completed_at_utc', v_existing.completed_at_utc
      );
    ELSIF v_existing.status = 'processing' THEN
      -- ── Stale Detection: Zombie Key Recovery ──────────────────────────
      -- Use the per-key threshold (default 5 min). Heavy commands set 30+.
      v_stale_threshold := (v_existing.stale_threshold_minutes || ' minutes')::INTERVAL;

      IF NOW() - v_existing.created_at_utc > v_stale_threshold THEN
        UPDATE public.idempotency_keys
           SET status = 'processing',
               response_code = NULL,
               response_body = NULL,
               completed_at_utc = NULL,
               created_at_utc = NOW()
         WHERE id = p_id AND user_id = p_user_id AND status = 'processing';

        RETURN jsonb_build_object(
          'hit', false,
          'status', 'processing',
          'acquired', true,
          'reclaimed_from_stale', true
        );
      END IF;

      -- Not stale yet — another thread is genuinely processing.
      RAISE EXCEPTION
        'IdempotencyProcessingException: Command is already being processed. '
        'key: %, command: %, user_id: %',
        p_id, p_command_path, p_user_id
      USING ERRCODE = 'unique_violation',
            DETAIL = 'Another request is processing this command. Retry or poll status.';
    ELSIF v_existing.status = 'error' THEN
      -- Previous attempt failed — allow retry by updating to 'processing'.
      UPDATE public.idempotency_keys
         SET status = 'processing',
             response_code = NULL,
             response_body = NULL,
             completed_at_utc = NULL
       WHERE id = p_id AND user_id = p_user_id AND status = 'error';
      RETURN jsonb_build_object(
        'hit', false,
        'status', 'processing',
        'acquired', true
      );
    END IF;
  END IF;

  -- Step 2: Key not found or was 'error' — try to register as 'processing'.
  INSERT INTO public.idempotency_keys (id, user_id, command_path, organization_id, status, created_at_utc)
  VALUES (p_id, p_user_id, p_command_path, p_organization_id, 'processing', NOW())
  ON CONFLICT (id, user_id) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  IF v_inserted = 0 THEN
    -- Race condition: another thread inserted the key between our check and insert.
    -- Re-check the status and per-key threshold.
    SELECT status, created_at_utc, COALESCE(stale_threshold_minutes, 5) AS stale_threshold_minutes
      INTO v_existing
      FROM public.idempotency_keys
     WHERE id = p_id AND user_id = p_user_id
     LIMIT 1;

    IF FOUND AND v_existing.status = 'completed' THEN
      RETURN jsonb_build_object(
        'hit', true,
        'status', 'completed',
        'response_code', v_existing.response_code,
        'response_body', v_existing.response_body,
        'completed_at_utc', v_existing.completed_at_utc
      );
    ELSIF FOUND AND v_existing.status = 'processing' THEN
      -- Stale detection for race condition path: use per-key threshold.
      v_stale_threshold := (v_existing.stale_threshold_minutes || ' minutes')::INTERVAL;
      IF NOW() - v_existing.created_at_utc > v_stale_threshold THEN
        UPDATE public.idempotency_keys
           SET status = 'processing',
               response_code = NULL,
               response_body = NULL,
               completed_at_utc = NULL,
               created_at_utc = NOW()
         WHERE id = p_id AND user_id = p_user_id AND status = 'processing';

        RETURN jsonb_build_object(
          'hit', false,
          'status', 'processing',
          'acquired', true,
          'reclaimed_from_stale', true
        );
      END IF;
    END IF;

    RAISE EXCEPTION
      'IdempotencyProcessingException: Command is already being processed (race condition). '
      'key: %, command: %, user_id: %',
      p_id, p_command_path, p_user_id
    USING ERRCODE = 'unique_violation',
          DETAIL = 'Race condition detected. Another request won the insert race.';
  END IF;

  -- Step 3: Key successfully registered as 'processing'.
  RETURN jsonb_build_object(
    'hit', false,
    'status', 'processing',
    'acquired', true
  );
END;
$$;

-- ── 8. Complete idempotency key (mark as completed with response body) ───────

CREATE OR REPLACE FUNCTION public.complete_idempotency_key(
  p_id            TEXT,
  p_user_id       UUID,
  p_response_code INT,
  p_response_body JSONB
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.idempotency_keys
     SET status = 'completed',
         response_code = p_response_code,
         response_body = p_response_body,
         completed_at_utc = NOW()
   WHERE id = p_id
     AND user_id = p_user_id
     AND status = 'processing';

  -- If no rows updated, the key may have been rolled back or already completed.
  -- This is a no-op — the caller should log a warning.
  IF NOT FOUND THEN
    RAISE WARNING 'complete_idempotency_key: no processing key found for id=%, user_id=%', p_id, p_user_id;
  END IF;
END;
$$;

-- ── 9. Fail idempotency key (mark as error) ─────────────────────────────────

CREATE OR REPLACE FUNCTION public.fail_idempotency_key(
  p_id            TEXT,
  p_user_id       UUID,
  p_response_code INT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.idempotency_keys
     SET status = 'error',
         response_code = p_response_code,
         completed_at_utc = NOW()
   WHERE id = p_id
     AND user_id = p_user_id
     AND status = 'processing';

  IF NOT FOUND THEN
    RAISE WARNING 'fail_idempotency_key: no processing key found for id=%, user_id=%', p_id, p_user_id;
  END IF;
END;
$$;

-- ── 10. Verification ─────────────────────────────────────────────────────────

DO $$
BEGIN
  -- Verify table exists.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
     WHERE table_schema = 'public'
       AND table_name   = 'idempotency_keys'
  ) THEN
    RAISE EXCEPTION 'idempotency_keys table was not created';
  END IF;

  -- Verify indexes.
  PERFORM 1 FROM pg_indexes
   WHERE schemaname = 'public'
     AND tablename  = 'idempotency_keys'
     AND indexname  = 'idx_idempotency_keys_user_status';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'idx_idempotency_keys_user_status index was not created';
  END IF;

  -- Verify cleanup function exists.
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc
     WHERE proname = 'cleanup_expired_idempotency'
  ) THEN
    RAISE EXCEPTION 'cleanup_expired_idempotency function was not created';
  END IF;

  -- Verify RPC functions exist.
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'try_acquire_idempotency_key'
  ) THEN
    RAISE EXCEPTION 'try_acquire_idempotency_key RPC was not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'complete_idempotency_key'
  ) THEN
    RAISE EXCEPTION 'complete_idempotency_key RPC was not created';
  END IF;

  -- Verify RLS is enabled.
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
     WHERE schemaname = 'public'
       AND tablename  = 'idempotency_keys'
       AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on idempotency_keys';
  END IF;

  RAISE NOTICE '✅ Idempotency keys infrastructure installed successfully (INV-33)';
END
$$;
