-- Suppress DROP TRIGGER/POLICY IF EXISTS NOTICEs.
SET client_min_messages TO 'WARNING';

-- =============================================================================
-- Migration: WS-4 Telegram Evidence Bot
--
-- Tables: telegram_binding_tokens, telegram_chat_bindings,
--         telegram_evidence_uploads
-- RPC:    consume_telegram_binding_token
-- Fn:     check_telegram_rate_limit
-- Bucket: telegram_evidence (10 MB cap, matches Telegram file API limit)
--
-- INV-1:  Tenant isolation via organization_id on all tables.
-- INV-6:  UTC everywhere (timestamptz).
-- INV-7:  All tables append-only; DELETE blocked by trigger.
-- INV-9:  SHA-256 forensic hash mandatory on evidence records.
-- INV-18: Zero-Trust — Telegram filenames/metadata never trusted.
-- =============================================================================

-- ── 1. telegram_binding_tokens ───────────────────────────────────────────────
--
-- Short-lived 8-char code generated by operator; consumed by Telegram bot
-- to bind a driver's chat_id to their profile.
--
-- Alphabet: ABCDEFGHJKMNPQRSTUVWXYZ23456789 (32 unambiguous chars, 40 bits).
-- Ambiguous chars excluded: 0/O, 1/I/L.
-- Low entropy compensated by 15-minute TTL.

CREATE TABLE IF NOT EXISTS public.telegram_binding_tokens (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     UUID        NOT NULL,
  driver_id           UUID        NOT NULL REFERENCES public.drivers(id),
  created_by_user_id  UUID        NOT NULL,

  code                TEXT        NOT NULL UNIQUE
    CONSTRAINT chk_tbt_code_format
      CHECK (code ~ '^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{8}$'),

  expires_at_utc      TIMESTAMPTZ NOT NULL
    CONSTRAINT chk_tbt_expires_window
      CHECK (
        expires_at_utc > created_at_utc
        AND expires_at_utc <= created_at_utc + INTERVAL '15 minutes'
      ),

  -- Stamped once (NULL → timestamp) when bot consumes the code. Never reset.
  used_at_utc         TIMESTAMPTZ,

  created_at_utc      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tbt_code
  ON public.telegram_binding_tokens (code);

CREATE INDEX IF NOT EXISTS idx_tbt_org_driver
  ON public.telegram_binding_tokens (organization_id, driver_id);

CREATE INDEX IF NOT EXISTS idx_tbt_expires
  ON public.telegram_binding_tokens (expires_at_utc)
  WHERE used_at_utc IS NULL;

-- Immutability: all fields frozen; used_at_utc may only transition NULL → timestamp once.
CREATE OR REPLACE FUNCTION public.prevent_tbt_immutable_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.used_at_utc IS NOT NULL AND
     NEW.used_at_utc IS DISTINCT FROM OLD.used_at_utc
  THEN
    RAISE EXCEPTION
      'telegram_binding_tokens: used_at_utc already stamped (INV-7). id: %', OLD.id
    USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.organization_id     IS DISTINCT FROM OLD.organization_id     OR
     NEW.driver_id           IS DISTINCT FROM OLD.driver_id           OR
     NEW.created_by_user_id  IS DISTINCT FROM OLD.created_by_user_id  OR
     NEW.code                IS DISTINCT FROM OLD.code                OR
     NEW.expires_at_utc      IS DISTINCT FROM OLD.expires_at_utc      OR
     NEW.created_at_utc      IS DISTINCT FROM OLD.created_at_utc
  THEN
    RAISE EXCEPTION
      'telegram_binding_tokens: immutable field mutation (INV-7). id: %', OLD.id
    USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tbt_no_immutable_update ON public.telegram_binding_tokens;
CREATE TRIGGER trg_tbt_no_immutable_update
  BEFORE UPDATE ON public.telegram_binding_tokens
  FOR EACH ROW EXECUTE FUNCTION public.prevent_tbt_immutable_mutation();

CREATE OR REPLACE FUNCTION public.prevent_tbt_delete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'telegram_binding_tokens is append-only (INV-7). DELETE blocked. id: %', OLD.id
  USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_tbt_no_delete ON public.telegram_binding_tokens;
CREATE TRIGGER trg_tbt_no_delete
  BEFORE DELETE ON public.telegram_binding_tokens
  FOR EACH ROW EXECUTE FUNCTION public.prevent_tbt_delete();

ALTER TABLE public.telegram_binding_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tbt_select_own_org ON public.telegram_binding_tokens;
CREATE POLICY tbt_select_own_org
  ON public.telegram_binding_tokens FOR SELECT
  USING (
    organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid
    AND (auth.jwt() -> 'app_metadata' ->> 'role') IN ('TENANT_ADMIN', 'OPERATOR')
  );

DROP POLICY IF EXISTS tbt_insert_operator ON public.telegram_binding_tokens;
CREATE POLICY tbt_insert_operator
  ON public.telegram_binding_tokens FOR INSERT
  WITH CHECK (
    organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid
    AND (auth.jwt() -> 'app_metadata' ->> 'role') IN ('TENANT_ADMIN', 'OPERATOR')
  );

-- Service role (webhook Edge Function via service_role key) stamps used_at_utc.
DROP POLICY IF EXISTS tbt_update_service ON public.telegram_binding_tokens;
CREATE POLICY tbt_update_service
  ON public.telegram_binding_tokens FOR UPDATE
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS tbt_select_super_admin ON public.telegram_binding_tokens;
CREATE POLICY tbt_select_super_admin
  ON public.telegram_binding_tokens FOR SELECT
  USING ((auth.jwt() -> 'app_metadata' ->> 'super_admin')::boolean IS TRUE);

-- ── 2. telegram_chat_bindings ────────────────────────────────────────────────
--
-- Persistent mapping of Telegram chat_id → driver_id within a tenant.
-- Re-binding is supported without DELETE: unbound_at_utc is stamped on the
-- old row, and a new row is inserted. Partial unique indexes enforce that
-- only one active binding exists per chat AND per driver simultaneously.

CREATE TABLE IF NOT EXISTS public.telegram_chat_bindings (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     UUID        NOT NULL,
  driver_id           UUID        NOT NULL REFERENCES public.drivers(id),

  -- BIGINT: Telegram chat IDs for groups/supergroups are large negatives.
  chat_id             BIGINT      NOT NULL,

  bound_at_utc        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- NULL = active; stamped when re-binding replaces this entry.
  unbound_at_utc      TIMESTAMPTZ,

  -- Forensic link: which token established this binding.
  binding_token_id    UUID        NOT NULL
    REFERENCES public.telegram_binding_tokens(id)
);

-- One active binding per chat_id (prevents two drivers sharing a chat).
CREATE UNIQUE INDEX IF NOT EXISTS idx_tcb_chat_active
  ON public.telegram_chat_bindings (chat_id)
  WHERE unbound_at_utc IS NULL;

-- One active binding per driver (single-chat policy).
CREATE UNIQUE INDEX IF NOT EXISTS idx_tcb_driver_active
  ON public.telegram_chat_bindings (driver_id)
  WHERE unbound_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS idx_tcb_org_driver
  ON public.telegram_chat_bindings (organization_id, driver_id);

CREATE INDEX IF NOT EXISTS idx_tcb_chat_id
  ON public.telegram_chat_bindings (chat_id);

-- Immutability: identity fields frozen; unbound_at_utc may only transition NULL → timestamp once.
CREATE OR REPLACE FUNCTION public.prevent_tcb_immutable_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.unbound_at_utc IS NOT NULL AND
     NEW.unbound_at_utc IS DISTINCT FROM OLD.unbound_at_utc
  THEN
    RAISE EXCEPTION
      'telegram_chat_bindings: unbound_at_utc already stamped (INV-7). id: %', OLD.id
    USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.organization_id   IS DISTINCT FROM OLD.organization_id  OR
     NEW.driver_id         IS DISTINCT FROM OLD.driver_id        OR
     NEW.chat_id           IS DISTINCT FROM OLD.chat_id          OR
     NEW.bound_at_utc      IS DISTINCT FROM OLD.bound_at_utc     OR
     NEW.binding_token_id  IS DISTINCT FROM OLD.binding_token_id
  THEN
    RAISE EXCEPTION
      'telegram_chat_bindings: immutable field mutation (INV-7). id: %', OLD.id
    USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tcb_no_immutable_update ON public.telegram_chat_bindings;
CREATE TRIGGER trg_tcb_no_immutable_update
  BEFORE UPDATE ON public.telegram_chat_bindings
  FOR EACH ROW EXECUTE FUNCTION public.prevent_tcb_immutable_mutation();

CREATE OR REPLACE FUNCTION public.prevent_tcb_delete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'telegram_chat_bindings is append-only (INV-7). DELETE blocked. id: %', OLD.id
  USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_tcb_no_delete ON public.telegram_chat_bindings;
CREATE TRIGGER trg_tcb_no_delete
  BEFORE DELETE ON public.telegram_chat_bindings
  FOR EACH ROW EXECUTE FUNCTION public.prevent_tcb_delete();

ALTER TABLE public.telegram_chat_bindings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tcb_select_own_org ON public.telegram_chat_bindings;
CREATE POLICY tcb_select_own_org
  ON public.telegram_chat_bindings FOR SELECT
  USING (
    organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid
    AND (auth.jwt() -> 'app_metadata' ->> 'role') IN ('TENANT_ADMIN', 'OPERATOR', 'AUDITOR')
  );

-- Service role (webhook) reads bindings to look up driver/org and inserts new bindings.
DROP POLICY IF EXISTS tcb_service_all ON public.telegram_chat_bindings;
CREATE POLICY tcb_service_all
  ON public.telegram_chat_bindings FOR ALL
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS tcb_select_super_admin ON public.telegram_chat_bindings;
CREATE POLICY tcb_select_super_admin
  ON public.telegram_chat_bindings FOR SELECT
  USING ((auth.jwt() -> 'app_metadata' ->> 'super_admin')::boolean IS TRUE);

-- ── 3. telegram_evidence_uploads ─────────────────────────────────────────────
--
-- Fully immutable append-only evidence records.
-- UNIQUE (chat_id, telegram_message_id) makes webhook retries idempotent at DB level.

CREATE TABLE IF NOT EXISTS public.telegram_evidence_uploads (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID        NOT NULL,
  driver_id             UUID        NOT NULL REFERENCES public.drivers(id),

  chat_id               BIGINT      NOT NULL,
  telegram_message_id   BIGINT      NOT NULL,

  -- Server-generated filename (UUID.ext); Telegram metadata is never used (INV-18).
  file_name             TEXT        NOT NULL,

  -- SHA-256 hex digest (INV-9).
  forensic_hash         TEXT        NOT NULL
    CONSTRAINT chk_teu_hash_length CHECK (char_length(forensic_hash) = 64),

  -- {org_id}/telegram/{chat_id}/{server_uuid}.{ext}
  storage_path          TEXT        NOT NULL,

  source                TEXT        NOT NULL DEFAULT 'telegram'
    CONSTRAINT chk_teu_source CHECK (source = 'telegram'),

  -- Best-effort link to an SLA execution set (nullable).
  linked_set_id         TEXT,

  uploaded_at_utc       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_teu_chat_message UNIQUE (chat_id, telegram_message_id)
);

CREATE INDEX IF NOT EXISTS idx_teu_org_driver
  ON public.telegram_evidence_uploads (organization_id, driver_id);

CREATE INDEX IF NOT EXISTS idx_teu_chat_id
  ON public.telegram_evidence_uploads (chat_id);

CREATE INDEX IF NOT EXISTS idx_teu_linked_set_id
  ON public.telegram_evidence_uploads (linked_set_id)
  WHERE linked_set_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_teu_org_uploaded_at
  ON public.telegram_evidence_uploads (organization_id, uploaded_at_utc DESC);

-- Fully immutable: no field may ever change after insert (INV-7, INV-9).
CREATE OR REPLACE FUNCTION public.prevent_teu_immutable_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'telegram_evidence_uploads: fully immutable (INV-7). UPDATE blocked. id: %', OLD.id
  USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_teu_no_update ON public.telegram_evidence_uploads;
CREATE TRIGGER trg_teu_no_update
  BEFORE UPDATE ON public.telegram_evidence_uploads
  FOR EACH ROW EXECUTE FUNCTION public.prevent_teu_immutable_mutation();

CREATE OR REPLACE FUNCTION public.prevent_teu_delete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'telegram_evidence_uploads: append-only (INV-7). DELETE blocked. id: %', OLD.id
  USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_teu_no_delete ON public.telegram_evidence_uploads;
CREATE TRIGGER trg_teu_no_delete
  BEFORE DELETE ON public.telegram_evidence_uploads
  FOR EACH ROW EXECUTE FUNCTION public.prevent_teu_delete();

ALTER TABLE public.telegram_evidence_uploads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS teu_select_own_org ON public.telegram_evidence_uploads;
CREATE POLICY teu_select_own_org
  ON public.telegram_evidence_uploads FOR SELECT
  USING (
    organization_id = (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid
    AND (auth.jwt() -> 'app_metadata' ->> 'role') IN ('TENANT_ADMIN', 'OPERATOR', 'AUDITOR')
  );

-- Service role (webhook) inserts evidence records.
DROP POLICY IF EXISTS teu_insert_service ON public.telegram_evidence_uploads;
CREATE POLICY teu_insert_service
  ON public.telegram_evidence_uploads FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS teu_select_super_admin ON public.telegram_evidence_uploads;
CREATE POLICY teu_select_super_admin
  ON public.telegram_evidence_uploads FOR SELECT
  USING ((auth.jwt() -> 'app_metadata' ->> 'super_admin')::boolean IS TRUE);

-- ── 4. RPC: consume_telegram_binding_token ───────────────────────────────────
--
-- Atomic: validates token → invalidates old bindings → inserts new binding.
-- Called by the webhook Edge Function with service_role client (no JWT).
-- SECURITY DEFINER bypasses RLS; caller trust comes from TELEGRAM_WEBHOOK_SECRET.

CREATE OR REPLACE FUNCTION public.consume_telegram_binding_token(
  p_code     TEXT,
  p_chat_id  BIGINT
)
RETURNS TABLE(driver_id UUID, organization_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_token public.telegram_binding_tokens%ROWTYPE;
BEGIN
  -- 1. Load and lock the token row (serializes concurrent attempts).
  SELECT * INTO v_token
    FROM public.telegram_binding_tokens
   WHERE code = p_code
     FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Token not found.'
      USING ERRCODE = 'no_data_found';
  END IF;

  -- 2. Validate: not expired.
  IF NOW() > v_token.expires_at_utc THEN
    RAISE EXCEPTION 'Token has expired.'
      USING ERRCODE = 'check_violation';
  END IF;

  -- 3. Validate: not already used.
  IF v_token.used_at_utc IS NOT NULL THEN
    RAISE EXCEPTION 'Token has already been used.'
      USING ERRCODE = 'unique_violation';
  END IF;

  -- 4. Invalidate existing active binding for this chat_id (re-bind flow).
  UPDATE public.telegram_chat_bindings
     SET unbound_at_utc = NOW()
   WHERE telegram_chat_bindings.chat_id = p_chat_id
     AND telegram_chat_bindings.unbound_at_utc IS NULL;

  -- 5. Invalidate existing active binding for this driver (single-chat policy).
  UPDATE public.telegram_chat_bindings
     SET unbound_at_utc = NOW()
   WHERE telegram_chat_bindings.driver_id = v_token.driver_id
     AND telegram_chat_bindings.unbound_at_utc IS NULL;

  -- 6. Insert new active binding.
  INSERT INTO public.telegram_chat_bindings (
    organization_id, driver_id, chat_id, bound_at_utc, binding_token_id
  ) VALUES (
    v_token.organization_id, v_token.driver_id, p_chat_id, NOW(), v_token.id
  );

  -- 7. Stamp token as used.
  UPDATE public.telegram_binding_tokens
     SET used_at_utc = NOW()
   WHERE id = v_token.id;

  RETURN QUERY SELECT v_token.driver_id, v_token.organization_id;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_telegram_binding_token(TEXT, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_telegram_binding_token(TEXT, BIGINT)
  TO authenticated;

-- ── 5. Function: check_telegram_rate_limit ───────────────────────────────────
--
-- DB-backed rate limiter: counts committed uploads in the last 60 seconds
-- for a given chat_id. Returns TRUE = allowed, FALSE = blocked.
-- Leverages the existing telegram_evidence_uploads table — no extra table needed.
-- Threshold: 10 uploads per chat per 60s (stops DoS, allows burst from drivers).

CREATE OR REPLACE FUNCTION public.check_telegram_rate_limit(p_chat_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COUNT(*) < 10
  FROM public.telegram_evidence_uploads
  WHERE chat_id = p_chat_id
    AND uploaded_at_utc > NOW() - INTERVAL '60 seconds';
$$;

REVOKE ALL ON FUNCTION public.check_telegram_rate_limit(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_telegram_rate_limit(BIGINT) TO authenticated;

-- ── 6. Storage bucket: telegram_evidence ─────────────────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'telegram_evidence',
  'telegram_evidence',
  false,
  10485760,  -- 10 MB — hard cap matching Telegram file API limit
  ARRAY[
    'image/jpeg', 'image/png', 'image/webp',
    'image/heic', 'image/heif',
    'video/mp4', 'video/quicktime',
    'application/pdf',
    'application/octet-stream'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Storage path: {org_id}/telegram/{chat_id}/{server_uuid}.{ext}

DROP POLICY IF EXISTS "telegram_evidence_select" ON storage.objects;
CREATE POLICY "telegram_evidence_select"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'telegram_evidence'
    AND (storage.foldername(name))[1] =
        (auth.jwt() -> 'app_metadata' ->> 'org_id')
  );

-- INSERT is service_role only (webhook uploads on behalf of driver).
DROP POLICY IF EXISTS "telegram_evidence_insert" ON storage.objects;
CREATE POLICY "telegram_evidence_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'telegram_evidence');

-- No DELETE policy — evidence is immutable (INV-7).
