-- Enable PostGIS extension for geolocation
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Drivers Table
CREATE TABLE public.drivers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name TEXT NOT NULL,
    license_number TEXT UNIQUE NOT NULL, -- CNH
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buses Table
CREATE TABLE public.buses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    plate TEXT UNIQUE NOT NULL, -- License Plate
    capacity INTEGER NOT NULL,
    model TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Routes Table (Imported from Static GTFS or Manual)
CREATE TABLE public.routes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    gtfs_route_id TEXT UNIQUE, -- External API ID (if any)
    name TEXT NOT NULL, -- Route Name (e.g., "809U-10 Cidade Universitária")
    agency_id TEXT, -- Agency ID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Trips Audit Table (The Truth Source)
-- Associates a Driver with a Bus on a specific Route, with a departure time.
CREATE TABLE public.trips_audit (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
    bus_id UUID REFERENCES public.buses(id) ON DELETE SET NULL,
    route_id UUID REFERENCES public.routes(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time TIMESTAMPTZ, -- Null while trip is active
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    
    -- Origin Metadata (API vs Manual)
    source_type TEXT DEFAULT 'manual' CHECK (source_type IN ('manual', 'api_gtfs', 'schedule')),
    external_trip_id TEXT -- Trip ID in external system (GTFS Realtime)
);

-- 5. Vehicle Positions Table (Realtime + History)
CREATE TABLE public.vehicle_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id UUID REFERENCES public.trips_audit(id) ON DELETE CASCADE,
    location GEOGRAPHY(POINT, 4326) NOT NULL, -- Latitude/Longitude
    speed DOUBLE PRECISION,
    heading DOUBLE PRECISION,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    
    -- Position Source Info (Truth Hierarchy: API > GPS Crowdsourcing)
    source TEXT NOT NULL CHECK (source IN ('api_public', 'driver_app_gps'))
);

-- Spatial Indexes for fast querying
CREATE INDEX idx_vehicle_positions_location ON public.vehicle_positions USING GIST (location);

-- Optional: RLS Policies (Row Level Security) - Basic Setup
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trips_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_positions ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for MVP simplicity, restrict in production)
CREATE POLICY "Public Read Access" ON public.drivers FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public.buses FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public.routes FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public.trips_audit FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public.vehicle_positions FOR SELECT USING (true);

-- Allow authenticated insert (for drivers/admin)
CREATE POLICY "Auth Insert" ON public.vehicle_positions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
